### ISSUE TITLE
Rustup?

### ISSUE THREAD

**Issue by benjsmi** [bcgov/von-network#10]
https://github.com/bcgov/von-network/blob/master/Dockerfile#L56-L59 has us grabbing rust using rustup.  I understand this is a typical way of installing Rust, but I was curious if it doesn't make more sense in *this context* to install it as an apt package, since that's how everything else is being installed?

https://packages.ubuntu.com/en/xenial/rustc works as well as https://packages.ubuntu.com/en/xenial/cargo in my testing, but they are indeed older versions of the language. I will PR if it seems like a worthwhile consideration. Otherwise just close me.

**Comment by nrempel** [comment]
Hey @benjsmi, things can absolutely be optimized here. We stood things up pretty hastily initially with the intention of circling back (around now)

We have someone who has been working on improved builds for some of our environments using Alpine Linux. If you would be interested in working on improving the build and opening a pull request, that would be fantastic! Bonus points if you want to use Alpine Linux to keep things slim.

**Comment by benjsmi** [comment]
Alpine specifically would be nice although I'm not sure if there exists a Rust package for alpine. I'll look into it.

**Comment by benjsmi** [comment]
There definitely is a rust package for alpine, but I'm realizing this: a lot of the Indy packages are only available for Debian and RPM package managers and Alpine doesn't have those. Alpine uses [apk](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management) for package management, so you'd need to setup and distribute builds of APKs for the Indy projects for this to be feasible. Is something like that in the works?
