### ISSUE TITLE
EdX Course Redirect

### ISSUE THREAD

**Issue by andrewBSTan** [bcgov/von-network#102]
Hi,
Through the EdX Course on Aries Developer, gets redirected to this site : https://github.com/bcgov/von-network/blob/master/docs/UsingVONNetwork.md

Is the git clone the right depository as its not found.

Thanks.

Regards,
Andrew

**Comment by swcurran** [comment]
Dang, no. It should by "bcgov" instead of "hyperledger" in the URL.

I'll fix that tomorrow.

Thanks for letting us know.

**Comment by andrewBSTan** [comment]
Thanks Stephen and seems can't get the von network up in windows environment.

Andrew

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by swcurran** [comment]
That seems very odd. It's used a lot on Windows every day. Perhaps attach
some logs?

You now have to explicitly request logs. To get logs:

As you start use the "--logs" option. Once running, use `,/manage logs`
command.

To see if it is running, check: `docker ps`.

**Comment by WadeBarnes** [comment]
@andrewBSTan, I’m a Windows user and so the majority of the testing for `von-network`.  I had it running on Windows from a clean build yesterday.  The scripts are written in bash, so you need to use a Git Bash Shell at minimum (that’s what I use to run all of our projects).

Please include error logs.  That will help us troubleshoot for you.

**Comment by andrewBSTan** [comment]
Hi Barnes,

Please find attached.  Am using Docker Toolbox as am not on Windows 10 Professional.

I start-up the Docker Toolbox before I start up the Git Bash Shell environment and using the Bash Shell, follow the steps of ./manage build followed by ./manage start –logs

Appreciate your guidance.

Thanks.

Regards,
Andrew

**Comment by WadeBarnes** [comment]
It appears the nodes are starting and connecting just fine.  I don’t see any logs from the webserver.  If you wait for a bit do you ever see any logs from the webserver starting up?  The webserver startup is delayed for 10 seconds to allow the nodes to get a head start on their initialization.

**Comment by swcurran** [comment]
Instructions fixed in #103

**Comment by WadeBarnes** [comment]
@andrewBSTan, Have a look at the solution in https://github.com/bcgov/von-network/issues/107, you are likely running into the same issues.

**Comment by WadeBarnes** [comment]
@andrewBSTan, We're you able to resolve the issues you were having?
