### ISSUE TITLE
Cannot start webserver - python error - Ubuntu 18.04 in Vagrant Windows

### ISSUE THREAD

**Issue by martinporopat** [bcgov/von-network#110]
Following https://github.com/bcgov/von-network/blob/master/docs/UsingVONNetwork.md
Ubuntu 18.04 in Vagrant on Windows

When running sudo ./manage build
in step "pip install --no-cache-dir -r server/requirements.txt"

_Successfully installed MarkupSafe-1.1.1 aiohttp-jinja2-1.1.2 jinja2-2.11.2 meld3-2.0.1 pyyaml-5.1.2 _supervisor-4.0.4
You are using pip version 9.0.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 345757aaee0b__

When running: sudo ./manage start --logs

_webserver_1  | 2020-05-01 22:55:06,855|WARNING|libindy.py|_indy_loop_callback: Function returned error
webserver_1  | 2020-05-01 22:55:06,860|ERROR|anchor.py|Initialization error:
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/server/anchor.py", line 221, in _open_pool
webserver_1  |     self._pool = await pool.open_pool_ledger(pool_name, json.dumps(pool_cfg))
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/indy/pool.py", line 83, in open_pool_ledger
webserver_1  |     open_pool_ledger.cb)
webserver_1  | indy.error.PoolLedgerTimeout
webserver_1  |
webserver_1  | The above exception was the direct cause of the following exception:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/server/anchor.py", line 314, in open
webserver_1  |     await self._open_pool()
webserver_1  |   File "/home/indy/server/anchor.py", line 223, in _open_pool
webserver_1  |     raise AnchorException("Error opening pool ledger connection") from e
webserver_1  | server.anchor.AnchorException: Error opening pool ledger connection
webserver_1  | 2020-05-01 22:55:06,906|INFO|server.py|--- Trust anchor initialized ---_

![image](https://user-images.githubusercontent.com/3036063/80847657-d75a9c00-8be6-11ea-839d-cdc9c444ccc3.png)

![image](https://user-images.githubusercontent.com/3036063/80847577-91053d00-8be6-11ea-8988-58b70bc471a9.png)

**Comment by WadeBarnes** [comment]
Based on the screenshot of the log it appears the nodes have not finished starting up.

- Was this on the first attempt?
- Are you able to run the commands without the using `sudo`?

Try:
- `./manage stop`
- Wait for all of the containers to shutdown.
- `./manage start --log`

**Comment by martinporopat** [comment]
> Based on the screenshot of the log it appears the nodes have not finished starting up.
> 
> * Was this on the first attempt?
> * Are you able to run the commands without the using `sudo`?
> 
> Try:
> 
> * `./manage stop`
> * Wait for all of the containers to shutdown.
> * `./manage start --log`

It wasnt on first attemp, I got it working before.
I am able to run without sudo, but same issue :S

This step is the one that fails when ./manage Build or Rebuild:
- RUN pip install --no-cache-dir -r server/requirements.txt

Error:
![image](https://user-images.githubusercontent.com/3036063/81025180-310fd000-8e4c-11ea-86ca-957c0b8ff7e2.png)


And then the Python error in Webserver_1. I think it should be some dependency but couldnt make it work.

**Comment by WadeBarnes** [comment]
Unless I'm missing something, I'm not seeing an error in the build log you provided.

**Comment by WadeBarnes** [comment]
With runtime error, try:
- `./manage down`
  - This will clear everything out and start fresh.
- `./manage start --log`

**Comment by WadeBarnes** [comment]
You could try adding an additional delay to the webserver startup here, https://github.com/bcgov/von-network/blob/master/docker-compose.yml#L25, to see if that helps with the startup issues on your machine.

**Comment by martinporopat** [comment]
Thanks @WadeBarnes 

I got it working again by changing https://github.com/bcgov/von-network/blob/c395635360426e20308c2a14bcf067d659eb7238/Dockerfile#L8
to
RUN pip install wheel; pip install virtualenv --upgrade;  pip install --no-cache-dir -r server/requirements.txt
