### ISSUE TITLE
Running as a VPS on an EC2 needs to ensure security groups are correct.

### ISSUE THREAD

**Issue by jcourt562** [bcgov/von-network#112]
Installing the von network on an AWS EC2 can result in the nodes failing to become fully active due to AWS security group configuration. 

If after starting the installed VON network with "./manage start" you see the following repeating pattern of messages in the "./manage log" output you need to check that your AWS security groups are set to allow communication between the EC2 instance public addresses.  This might be useful to call out in the  "Running the Network on a VPS" section of the README.md.  The reason is that the indy nodes are configured to listen on 0.0.0.0 but send outgoing node traffic to the public addresses not the private VPC addresses.  The public addresses usually have security restrictions applied, especially when you are testing a deployment.

_node2_1 | 2020-05-07 23:56:30,728|NOTIFICATION|primary_connection_monitor_service.py|Node2:0 primary has been disconnected for too long
node2_1 | 2020-05-07 23:56:30,729|INFO|primary_connection_monitor_service.py|Node2:0 The node is not ready yet so view change will not be proposed now, but re-scheduled.
node2_1 | 2020-05-07 23:56:30,730|INFO|primary_connection_monitor_service.py|Node2:0 scheduling primary connection check in 60 sec
node2_1 | 2020-05-07 23:56:30,730|NOTIFICATION|primary_connection_monitor_service.py|Node2:0 primary has been disconnected for too long
node2_1 | 2020-05-07 23:56:30,730|INFO|primary_connection_monitor_service.py|Node2:0 The node is not ready yet so view change will not be proposed now, but re-scheduled._

The suggested steps for deploying the VON VPS on an AWS EC2 node are (AWS components in **bold**) :   

- Create a **VPC** and configure the **Network ACL** to allow inbound traffic on port 22 AND inbound and outbound traffic on ports 9701-9708
- Deploy an ubuntu **Ec2** instance into a public subnet and configure a **Security Group** to allow inbound traffic on port 22 AND inbound and outbound traffic on ports 9701-9708
- For the outbound traffic rules on both the **Network ACL** and the **Security Group**  the destination IP will be the Public IP address of the **Ec2** instance you deploy (this will allow the nodes inside the docker container to call out to each another)
- For the inbound traffic rules on both the **Network ACL** and the **Security Group**  the source IP address will be the Public IP address of the **Ec2** instance AND any IP from which you will be running clients e.g. an ssh client or the indy-cli

**Comment by WadeBarnes** [comment]
@jcourt562, please add these updates to the documentation on your fork of the repository and submit the changes as a PR (Pull Request).

**Comment by swcurran** [comment]
If you are not familiar with github, let us know - we can do the PR. If you are, please make sure you sign your commit with "DCO" to make sure that we can accept it in the repo. It's a requirement for all Hyperledger contributions.  The contributors document in the repo has more details.

Thanks!

**Comment by jcourt562** [comment]
Hopefully I have created the Pull Request correctly, it is certainly signed.  Let me know if there is anything further required.

Thanks

John
________________________________

**Comment by WadeBarnes** [comment]
Resolved by https://github.com/bcgov/von-network/pull/113
