### ISSUE TITLE
In Ubuntu start command does execute

### ISSUE THREAD

**Issue by abhaypsoni** [bcgov/von-network#118]
Hi I am using Ubuntu machine and executed build command and it ran successfully. But start command doesn't work. Here is the output
![image](https://user-images.githubusercontent.com/16345316/84794114-7d395d00-b013-11ea-9555-68aa27c2f2d6.png)

**Comment by WadeBarnes** [comment]
@abhaypsoni, looks like you need to upgrade your version of Docker-Compose.

**Comment by abhaypsoni** [comment]
Thanks, It worked. hence closing it.
