### ISSUE TITLE
Can't write a schema definition to test ledger at http://test.bcovrin.vonx.io/

### ISSUE THREAD

**Issue by anhem115** [bcgov/von-network#119]
Currently, I'm following the steps at: https://github.com/bcgov/von-network/blob/master/docs/Writing%20Transactions%20to%20a%20Ledger%20for%20an%20Un-privileged%20Author.md
except that:
#1 I init my pool with the test ledger instead:
```./manage cli reset; ./manage cli init-pool localpool http://test.bcovrin.vonx.io/genesis```
#2 I register new DID for my agent and my endorser on the UI at `http://test.bcovrin.vonx.io` using the wallet seed as instruction. (However, when I try to run `did import` in my local wallet, I notice that the associated verkey in that test ledger is different with my verkey in my wallet, so I'm not why is that happen)
#3 I write the transaction to the test ledger as:
```
ledger get-nym did=WXwizNAUxGMB9QrgSDZG9T
ledger get-nym did=NFP8kaWvCupbDQHQhErwXb
ledger load-transaction file=/tmp/anh-permit.anh-co_endorser_signed_schema.txn
ledger custom context

```

and I got the following error:

```
Following NYM has been received.
Metadata:
+------------------------+-----------------+---------------------+---------------------+
| Identifier             | Sequence Number | Request ID          | Transaction time    |
+------------------------+-----------------+---------------------+---------------------+
| LibindyDid111111111111 | 23684           | 1592333926246546200 | 2020-06-16 18:49:33 |
+------------------------+-----------------+---------------------+---------------------+
Data:
+------------------------+------------------------+----------------------------------------------+----------+
| Identifier             | Dest                   | Verkey                                       | Role     |
+------------------------+------------------------+----------------------------------------------+----------+
| V4SGRU86Z58d6TV7PBUe6f | WXwizNAUxGMB9QrgSDZG9T | H6cXF5VtUv8bgqT8wXa1XGZFqBDUJ8hjefAnebghz74j | ENDORSER |
+------------------------+------------------------+----------------------------------------------+----------+
pool(localpool):indy> ledger get-nym did=NFP8kaWvCupbDQHQhErwXb
Following NYM has been received.
Metadata:
+------------------------+-----------------+---------------------+---------------------+
| Identifier             | Sequence Number | Request ID          | Transaction time    |
+------------------------+-----------------+---------------------+---------------------+
| LibindyDid111111111111 | 23245           | 1592333936373336900 | 2020-06-12 15:09:48 |
+------------------------+-----------------+---------------------+---------------------+
Data:
+------------------------+------------------------+----------------------------------------------+------+
| Identifier             | Dest                   | Verkey                                       | Role |
+------------------------+------------------------+----------------------------------------------+------+
| V4SGRU86Z58d6TV7PBUe6f | NFP8kaWvCupbDQHQhErwXb | Cah1iVzdB6UF5HVCJ2ENUrqzAKQsoWgiWyUopcmN3WHd | -    |
+------------------------+------------------------+----------------------------------------------+------+
pool(localpool):indy> ledger load-transaction file=/tmp/anh-permit.anh-co_endorser_signed_schema.txn
Transaction has been loaded: {"endorser":"WXwizNAUxGMB9QrgSDZG9T","identifier":"NFP8kaWvCupbDQHQhErwXb","operation":{"data":{"attr_names":["test_value"],"name":"anh-permit.anh-co","version":"1.0.0"},"type":"101"},"protocolVersion":2,"reqId":1592333696665373500,"signatures":{"NFP8kaWvCupbDQHQhErwXb":"4oH8NqJBQyxYoYPq3NyUF1ZYVSQGxuSnsUUF3JWpd6PB4vBwuquwzwYieHynBnzADVu3FoM9YvQdL9UFeiTKqeAh","WXwizNAUxGMB9QrgSDZG9T":"5PLLUWjDtcfxDrPmRUcwzvxxML5qpFw7tkFmgr8rkVAG3wXLkAkiyr9xnBFcpgcNixENDFRXy9VfvB4nttAGEKRv"}}
pool(localpool):indy> ledger custom context
Transaction stored into context: "{\"endorser\":\"WXwizNAUxGMB9QrgSDZG9T\",\"identifier\":\"NFP8kaWvCupbDQHQhErwXb\",\"operation\":{\"data\":{\"attr_names\":[\"test_value\"],\"name\":\"anh-permit.anh-co\",\"version\":\"1.0.0\"},\"type\":\"101\"},\"protocolVersion\":2,\"reqId\":1592333696665373500,\"signatures\":{\"NFP8kaWvCupbDQHQhErwXb\":\"4oH8NqJBQyxYoYPq3NyUF1ZYVSQGxuSnsUUF3JWpd6PB4vBwuquwzwYieHynBnzADVu3FoM9YvQdL9UFeiTKqeAh\",\"WXwizNAUxGMB9QrgSDZG9T\":\"5PLLUWjDtcfxDrPmRUcwzvxxML5qpFw7tkFmgr8rkVAG3wXLkAkiyr9xnBFcpgcNixENDFRXy9VfvB4nttAGEKRv\"}}".
Would you like to send it? (y/n)
y
Transaction has been rejected: The action is forbidden
```
And If I tried to do it again. I got another error (look like a time out error):

```
Transaction response has not been received
```

When I checked the logs at `./manage logs`, I found an error log:

```
webserver_1  | 2020-06-16 19:04:59,213|ERROR|libindy.py|	src/services/pool/state_proof/mod.rs:86 | Given signature is not for current root hash, aborting
```

but I'm not sure whether is that relevant.

I currently get stuck at this point. My goal is to write my own schema to the test ledger at the moment.

**Comment by WadeBarnes** [comment]
Can you provide some information regarding your agent implementation?

**Comment by WadeBarnes** [comment]
Of the 2 DIDs you listed only `NFP8kaWvCupbDQHQhErwXb` exists on the ledger and it does not have the rights to write to the ledger.

**Comment by anhem115** [comment]
Yeah, so I didn't run any orgbook or von-agent-template, I just run the von-network in this case.
I used the following information to register the DID on test ledger as:

```
0000000000000000000000000MyAgent, role "(None)"
DID : NFP8kaWvCupbDQHQhErwXb 
Verkey in test ledger: Cah1iVzdB6UF5HVCJ2ENUrqzAKQsoWgiWyUopcmN3WHd
Verkey in my local wallet when import:  ~48PoT55RW8yCtkyuzsiQfy

ENDORSER543210000000000000000000, role "Endorser"
DID : WXwizNAUxGMB9QrgSDZG9T  
Verkey in test ledger:  H6cXF5VtUv8bgqT8wXa1XGZFqBDUJ8hjefAnebghz74j
Verkey in my local wallet when import: ~7BE47kfBmP54em38g64pgX
```

**Comment by anhem115** [comment]
Ok, I found that I can't create the Endorser in the test ledger, there is no record about the creation of the DID though it could show it was created successfully `WXwizNAUxGMB9QrgSDZG9T`. I'm not sure whether that is a bug of the test ledger?
![image](https://user-images.githubusercontent.com/11781639/84821725-2a46b200-afe1-11ea-95ae-2aa06b603571.png)

**Comment by WadeBarnes** [comment]
I see a schema, cred def, and endpoint registered for `NFP8kaWvCupbDQHQhErwXb` now; http://test.bcovrin.vonx.io/browse/domain?page=1&query=NFP8kaWvCupbDQHQhErwXb&txn_type=

**Comment by anhem115** [comment]
Yeah, but that is the old one. Right now, I try to create a new DID in the test ledger as my screenshot above but it does not show up in the transaction log.

**Comment by WadeBarnes** [comment]
I just reloaded the ledger.  I'll give it some time to cache the transactions for search and we'll see if things show up better.

**Comment by WadeBarnes** [comment]
The transactions have been loaded for search.  There is more info showing now;
- http://test.bcovrin.vonx.io/browse/domain?page=1&query=NFP8kaWvCupbDQHQhErwXb&txn_type=
- http://test.bcovrin.vonx.io/browse/domain?page=1&query=WXwizNAUxGMB9QrgSDZG9T&txn_type=

**Comment by anhem115** [comment]
Thank you @WadeBarnes , it's a bit weird when I could get the successful result by ledger get-nym did="WXwizNAUxGMB9QrgSDZG9T", so I thought it was ok.

**Comment by WadeBarnes** [comment]
Two things to check:
- List the DIDs in your wallet; https://github.com/bcgov/von-network/blob/master/cli-scripts/did-list#L7
- Review the format of your txn file to ensure it is flat and does not contain any unexpected white space or non-printable characters.

**Comment by WadeBarnes** [comment]
You're provided enough information that I could try writing the test txn to the ledger to see if it works for me.

**Comment by anhem115** [comment]
Thank you. I think I will close this issue.
