### ISSUE TITLE
Running Nodes on different machines

### ISSUE THREAD

**Issue by Primordium** [bcgov/von-network#121]
I have Von-network running on 2 different machines, the first one with default values, and the second one is running with GENESIS_URL pointing to the first one, but with this setup, the 4 nodes are running only on the first machine.

Is there any command to run 2 nodes one in each machine, like you see in indy-node documentation
[https://github.com/hyperledger/indy-node/blob/master/docs/source/start-nodes.md](url) in the section Remote Test Network Example,

And will the UI reflect/update with info from the second node, running on a different machine, and also, will the genesis file reflect this changes with the new IPs and port.

theres a script [https://github.com/bcgov/von-network/blob/master/scripts/start_node.sh](url) but I'm failing to use it.

**Comment by WadeBarnes** [comment]
Starting `von-network` on a machine creates a complete ledger consisting on 4 nodes as described in the document.  I assume you are attempting to start each node on a separate machine and join them together as described in the [Remote Test Network Example](https://github.com/hyperledger/indy-node/blob/master/docs/source/start-nodes.md#remote-test-network-example) section of the document.  If you want to simply run a ledger for test purposes the nodes do not need to be run on a separate machine.

To host a ledger that is accessible to other machines, you run;
```
./manage start <host_ip_address>
```
- Where `<host_ip_address>` is the network (or publicly) accessible IP address of the host machine on which you are running `von-network`.

The process is described in step 5 of [Running the Network on a VPS](https://github.com/bcgov/von-network#running-the-network-on-a-vps), but this can be done on any machine.

Hosted examples of this:
- http://dev.bcovrin.vonx.io/
- http://test.bcovrin.vonx.io/

Additional info:
- Running an instance of `von-network` with the GENESIS_URL pointing at another ledger as described here [Running the web server in Docker against another ledger](https://github.com/bcgov/von-network#running-the-web-server-in-docker-against-another-ledger) simple starts an instance of the ledger browser connected to the specified ledger.  It does not start any nodes, it just attaches the UI to the specified pool of nodes.
- The scripts in https://github.com/bcgov/von-network/tree/master/scripts, are all used internally by the indy-node containers at runtime, they are not meant to be run by a user from the command line outside a running container.

**Comment by Primordium** [comment]
Thank you for the answer, I will try to explain what I'm trying to achieve with this.

```
To host a ledger that is accessible to other machines, you run;

./manage start <host_ip_address>
Where <host_ip_address> is the network (or publicly) accessible IP address of the host machine on which you are running von-network.
```

in this case what would happen, if I understand correcly, this would only start the ledger browser while using a ledger on a different machine.

What I'm trying to do is somthing like:

1 - Machine 1 - 1 node
2 - Machine 2 - 1 node

if I access the von-network web in both machines I would get the state of both nodes.
They would be part of the same "network" but running on different machines

2 nodes would be enough and it is what I'm trying to achieve. This setup is for testing porpose.

**Comment by WadeBarnes** [comment]
```
in this case what would happen, if I understand correcly, this would only start the ledger browser while using a ledger on a different machine.
```
No, running `./manage start <host_ip_address>` starts a complete ledger with 4 nodes and a ledger browser, with the pool being accessible to other machines.

**Comment by WadeBarnes** [comment]
What you describe is possible, but is not supported by `von-network` out of the box.  Can you provide more information on the use case for what you are doing?

**Comment by Primordium** [comment]
So in that case what would be the steps to create on the first machine 1 node and only one (if possible)

And after how would I start the second node on the second machine.

And in the end accessing the ledger browser in any of the machines(if possible) or just the first one I would get the state of both nodes.

**Comment by Primordium** [comment]
> What you describe is possible, but is not supported by `von-network` out of the box. Can you provide more information on the use case for what you are doing?

Have 2 machines running, (servers in this case), I want for each machine to have one and only one node, but should be able to "access" both nodes, so if I create a DID on the first machine in the node1, I should be able on the second machine to resolve it, while also beeing capable to see the changes in the ledger browser.

**Comment by WadeBarnes** [comment]
I believe 4 nodes is the minimum you can have.  What you describe is possible but it's not the way `von-network` was originally intended to be setup and used.  You could look at adding support for that use case and contributing to the project.

**Comment by WadeBarnes** [comment]
Discussed over DM the potential of @Primordium exploring and adding support via PR.  Closing this issue.
