### ISSUE TITLE
Search field of Sovrin Main Network Browser is not working

### ISSUE THREAD

**Issue by fredericoschardong** [bcgov/von-network#139]
Hi,

If I put the bits of information together correctly, you are the creator (and hopefully the maintainer) of [Sovrin Main Network Browser](https://sovrin-mainnet-browser.vonx.io/) and [BCSovrin Temp Prod Network Browser](http://prod.bcovrin.vonx.io/). Is that so? If that's the case, could you possibly fix the [Sovrin Main Network Browser](https://sovrin-mainnet-browser.vonx.io/)? The filters do not work and it is not possible to use the search field.

Thank you.

**Comment by WadeBarnes** [comment]
@fredericoschardong, I've restarted it.  It will take a while to reload the transactions to the point the search will work again.

**Comment by swcurran** [comment]
In the meantime, you can also use https://indyscan.io as an alternative.

**Comment by fredericoschardong** [comment]
Thank you, @WadeBarnes and @swcurran. I am using indyscan as well. My goal is to compare both searching tools with one that I am building. Do you happen to know if there are any other searching tools for Sovrin? I am only aware of these two.

**Comment by swcurran** [comment]
That's all that I know of.  Are you aware of indy-vdr (ledger interface), indy-node-monitor and indy-ledger-monitor.  They are not browsers, but tools to interact with an indy ledger?

I'm interested to hear more about what you are building.

**Comment by fredericoschardong** [comment]
I was not aware of such tools, thank you. We are in the process of evaluating our tool and writing the paper. Unfortunately, I can not share any more information about it at this stage. I will be more than happy to send you a copy of the paper and point you to our code once the paper is published, which should take a few months.

**Comment by fredericoschardong** [comment]
By the way, who are the authors of your browsing tool? I have found a couple of pull requests from different people and I am not sure who should be acknowledged as an author, and in what order.

**Comment by swcurran** [comment]
@andrewwhitehead wrote the majority of it, with help from other developers on the BC Gov Digital Trust Services team.

**Comment by WadeBarnes** [comment]
@fredericoschardong, Here are links to the other projects:
- [indy-node-monitor](https://github.com/hyperledger/indy-node-monitor)
- [indy-ledger-monitor](https://github.com/didx-xyz/indy-ledger-monitor) - Currently still in the early stages.  It will be contributed to Hyperledger soon.
- [indy-ledger-graph](https://github.com/didx-xyz/indy-ledger-graph) - Provides visualization (GraphQL interface) to the data from [indy-ledger-monitor](https://github.com/didx-xyz/indy-ledger-monitor)
- These are all build on [indy-vdr](https://github.com/hyperledger/indy-vdr)

**Comment by fredericoschardong** [comment]
> @fredericoschardong, I've restarted it. It will take a while to reload the transactions to the point the search will work again.

Should it take more than a day or two? I have been monitoring the browser and the txn counter seems to be stuck at 58535.

**Comment by WadeBarnes** [comment]
I'll have to take a closer look.

**Comment by WadeBarnes** [comment]
@fredericoschardong, we've moved the ledger browser over to another hosting environment.  It seems to be functioning much better.  It may not be fully synced yet, but search is working.  Please give it a try.

**Comment by fredericoschardong** [comment]
Thank you, @WadeBarnes. It is much more responsive now and the number of txns (58997 right now) matches the ledger.

I see there are new types of transactions, such as TXN_AUTHOR_AGREEMENT and CHANGE_KEY, which are not listed in indyscan. Selecting them returns 0 txns. What are those? 

Furthermore, filtering for NYM or SCHEMA returns way fewer txns as exist in the ledger, which can be confirmed in indyscan.

**Comment by WadeBarnes** [comment]
@fredericoschardong, refer to [hyperledger/indy-plenum](https://github.com/hyperledger/indy-plenum) for information in the transactions.

As for filtering on NYM or SCHEMA, can you provide an example of how you're filtering.  If you are not including a search parameter it may only be providing a sub-set of results.

**Comment by fredericoschardong** [comment]
@WadeBarnes I don't know what happened when I tested it three days ago, but now it works just fine. I can filter for transaction type and search for a string within those results as expected. Thank you!
