### ISSUE TITLE
Tag versions to allow stable point references

### ISSUE THREAD

**Issue by jcourt562** [bcgov/von-network#145]
VON network is an extremely useful tool for developers before they are ready to brave the public test ledgers on Sovrin, Indicio etc.

It would be great If we could just tag the current version so that future development, that might break the HEAD does not effect people pulling the repo.  I know they could just pull a specific commit ref but a tag makes it more obvious which one to use.

**Comment by swcurran** [comment]
@WadeBarnes -- what do you think?  Presumably the locked version would have to lock down dependencies, at least to some extent. For example, using a specific version of von-image, which in turn would use a specific version of Indy.

**Comment by mgmgwi** [comment]
@WadeBarnes: Would you consider this PR IDunion/von-network/pull/1 ? If it's ok, I will create a new PR here. The idea is to provide
  a) a ready to use image (without having to build it), and
  b) provide labels for specific versions

**Comment by WadeBarnes** [comment]
> @WadeBarnes: Would you consider this PR [IDunion/pull/1](https://github.com/IDunion/von-network/pull/1) ? If it's ok, I will create a new PR here. The idea is to provide
> a) a ready to use image (without having to build it), and
> b) provide labels for specific versions

@mgmgwi, Absolutely.  I've only had a quick look, but it looks good.  We may end up making a repository over here (https://hub.docker.com/u/bcgovimages) for the built image, but feel free to submit the PR and I'll start having a closer look.

**Comment by WadeBarnes** [comment]
@mgmgwi, Thanks for https://github.com/bcgov/von-network/pull/146, I've merged it and made a few updates to ensure we're not proliferating `von-network` images across all the forks.  I also added a `latest` tag.  Let me know what you think.

**Comment by WadeBarnes** [comment]
@jcourt562, @mgmgwi, @swcurran, Do any of you have an opinion on the version number for the initial release tag?

**Comment by mgmgwi** [comment]
> @mgmgwi, Thanks for PR #146, I've merged it and made a few updates to ensure we're not proliferating `von-network` images across all the forks. I also added a `latest` tag. Let me know what you think. I also renamed the image to `von-network-base` to be consistent with what the `manage` script and `docker-compose` file are expecting.

That's great. Thank you very much!

> Do any of you have an opinion on the version number for the initial release tag?

Not really, maybe you align this to `bcgovimages/von-image:node-1.12-3` :man_shrugging:

**Comment by WadeBarnes** [comment]
> Not really, maybe you align this to `bcgovimages/von-image:node-1.12-3` 🤷‍♂️

That was my initial thought too, however we have made other updates to `von-network` itself in the past (and likely to again in the future) that warrant version bumps.  So it's likely best to give `von-network` it's own version, I'm just wondering where we should start; `<1.0.0.` or `>=1.0.0`

**Comment by mgmgwi** [comment]
> > Not really, maybe you align this to `bcgovimages/von-image:node-1.12-3` man_shrugging
> 
> That was my initial thought too, however we have made other updates to `von-network` itself in the past (and likely to again in the future) that warrant version bumps. So it's likely best to give `von-network` it's own version, I'm just wondering where we should start; `<1.0.0.` or `>=1.0.0`

According to [semver.org](https://semver.org/#how-do-i-know-when-to-release-100) you probably should start with `>=1.0.0`.

**Comment by jcourt562** [comment]
Happy with any version but since it really is in effectively public use already I would suggest just starting with 1.0.0

**Comment by WadeBarnes** [comment]
Done, see https://github.com/bcgov/von-network/releases
