### ISSUE TITLE
Problem starting the service 

### ISSUE THREAD

**Issue by jahidulrudro** [bcgov/von-network#147]
Hi 
I have cloned the latest repo and run /manage build it was successful but after than when try to run ./manage start it show up followings :
<img width="949" alt="Capture" src="https://user-images.githubusercontent.com/14016993/122464079-fb469000-cfe8-11eb-9f1f-984a0ed7c194.PNG">

Please suggest me what i can do at this situation. 
Thanks in advance.

**Comment by swcurran** [comment]
Hmmm...just tried a fresh clone on Ubuntu and it's working fine for me -- and in many other places.

What OS are you running on?

**Comment by jahidulrudro** [comment]
I am running Ubuntu 16.04 LTS version

**Comment by jahidulrudro** [comment]
Hi I have installed fresh ubuntu 16.04 and tried still when run ./manage start it shows the same.  ./manage build is working fine but when try to run ./manage start this happening

**Comment by andrewwhitehead** [comment]
Can you check the docker-compose version?

**Comment by jahidulrudro** [comment]
docker-compose version 1.18.0, build 8dd22a9

**Comment by jahidulrudro** [comment]
and when run docker ps it shows empty container list even though ./manage build was completed successfully ...

**Comment by jahidulrudro** [comment]
downgrade the docker-compose version now it's working.

docker-compose version 1.29.2, build 5becea4c

thanks for the support
