### ISSUE TITLE
How to change static page content 

### ISSUE THREAD

**Issue by jahidulrudro** [bcgov/von-network#149]
Hi 
Thank you for your support.  I would like to change static page content. Like as example if i want to change localhost to any other name or want to remove Contributed by the Province of British Columbia how to do that. I changed at static files and it seems not working. 

I will be grateful if you provide an accurate guide line.

**Comment by WadeBarnes** [comment]
Information on how to configure and customize the labeling of a running `von-network` instance can be found here; https://oauth-openshift.apps.silver.devops.gov.bc.ca/oauth/token/display

For example, here is the startup command for http://test.bcovrin.vonx.io/:
```
./manage start 138.197.138.255 WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=BCovrin Test" "INFO_SITE_TEXT=vonx.io" "INFO_SITE_URL=https://vonx.io/"
```

Anything beyond that will require updates to the static content itself.  For example; https://github.com/bcgov/von-network/blob/master/server/static/header.html

Any code changes like this will require a build `./manage build` or rebuild `./manage rebuild` to be picked up by the base image.

**Comment by jahidulrudro** [comment]
Thank you for your kind cooperation. I am wondering do you have any step guideline that we can follow to connect our indy agent with our node ..I tried to change the genesis url but still agent shows error with varkey ..Maybe i have to register a wallet i am confused. If you so kind to help to suggest the step i will be grateful. Thank you

**Comment by WadeBarnes** [comment]
What type of agent are you using and what steps are you taking to get to the point where you get the error?

**Comment by WadeBarnes** [comment]
Also your second question appears to be unrelated to your first.  If these are two separate issues, you should enter them as separate issues.

**Comment by jahidulrudro** [comment]
if you have time to look at this 
https://github.com/TrustNetPK/cov-id-cloud-agent

these are currently connected with http://greenlight.bcovrin.vonx.io and working fine for me i want to connect those agents with my localhost VON network node.

**Comment by WadeBarnes** [comment]
`greenlight.bcovrin.vonx.io` is a hosted instance of `von-network`.  Typically the switch from a hosted instance to a local instance is as simple as changing `http://greenlight.bcovrin.vonx.io/genesis` to `http://localhost:9000/genesis` for example, though it depends on where your agent is running too, as the network needs to be accessible to the agent.  You'll still need to register the agent's DID on the ledger.

What is the full error you are getting?
Where is your `von-network` instance running and what command did you use to start it?
Where is your agent running?

Here is and example docker compose setup for an agent to connect to a locally running `von-network` instance; https://github.com/bcgov/aries-vcr/blob/master/docker/docker-compose.yml.  Instructions on how to run the example can be found here; https://github.com/bcgov/aries-vcr/tree/master/docker#running-theorgbook-with-docker-compose

**Comment by jahidulrudro** [comment]
hi http://119.235.7.30:8999/ this my application which issue a certificate and store bcovrin network i change genesis url from green light to http://18.140.84.29:9000/genesis my local installation of VON network and register unique seed as well. 
I am getting following errors when start to run my agents 
<img width="939" alt="Capture" src="https://user-images.githubusercontent.com/14016993/123145360-57009580-d48f-11eb-8af4-43ff433fb45e.PNG">

**Comment by jahidulrudro** [comment]
https://github.com/TrustNetPK/cov-id-cloud-agent
this is the agent i am using to connect indy with the VON network ..this one currently configure with green light so i change genesis url and as well as seed

**Comment by jahidulrudro** [comment]
Hi the issue has been solved thank you for your kind cooperation

**Comment by WadeBarnes** [comment]
@jahidulrudro, In the end, what did you do to resolve the issue?  Knowing would help others who encounter similar issues.
