### ISSUE TITLE
Document how to enable TAA, add support for enabling on startup

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-network#150]
Document the process for enabling a TAA in `von-network`.  For bonus points add support for enabling the TAA as a startup option.

Here is the process to enable TAA in `von-network`:
- The TAA and associated AML can be defined here; https://github.com/bcgov/von-network/tree/master/config
- Make copies of the samples and name them aml.json and taa.json , rebuild and start von-network.
- Those files will then get registered by; https://github.com/bcgov/von-network/blob/master/server/anchor.py#L225
- By default they are ignored by GIT; https://github.com/bcgov/von-network/blob/master/.gitignore#L145-L147

**Comment by jcourt562** [comment]
I can probably take this. I want to get this working anyway for the SDK we publish using VON so it would be better to get it going in the public repo than something we craft individually.  It will also make the devel environment closer to the experience using the Public ledgers so thats a big win IMHO.

**Comment by swcurran** [comment]
That would be great.  I've been debating if we should automatically activate it on VON-Network and/or BCovrin.  Would break things, but makes stuff more realistic.  

If you can add an option on `./manage start` to activate the TAA, that would be very cool...

**Comment by jcourt562** [comment]
@swcurran yep I can do that.  I use VON so much it would be silly not to contribute to it :-)

**Comment by jcourt562** [comment]
@swcurran looking at the code it would seem that since the TAA addition requires a rebuild of the images it makes more sense to add the option to `./manage build` and `./manage rebuild`.   I am thinking of a `-taa` switch which if present will build the sample_aml.json and sample_taa.json into the images as @WadeBarnes has described.  Did you specifically want it to be part of the `./manage start` or is this an acceptable approach ?

**Comment by jcourt562** [comment]
@swcurran actually maybe the comment that a `rebuild` is necessary isn't true.  Looks like the docker-compose.yml is mounting the ./config not just including it in the von-network-base image that is built.

**Comment by jcourt562** [comment]
I have submitted the code changes to get this to work and hopefully not trounce on instances where a user has already created their own aml.json and taa.json on shutdown.   Not sure what documentation area really needs changing.  I updated the `manage` usage instructions to point people at the config/ files.   It seems pretty clear once you look at the config/ files what can go in them.

**Comment by WadeBarnes** [comment]
Implemented in https://github.com/bcgov/von-network/pull/152
