### ISSUE TITLE
TheOrgBook build error

### ISSUE THREAD

**Issue by stoicangelo** [bcgov/von-network#153]
von network is running in background.

Trying to build from TheOrgBook/docker/ with the following command 
`./manage build`

Getting the following error

> Building django image from bcgovimages/von-image:py36-1.7-ew-1-s2i...
---> Installing application source ...
---> Installing dependencies ...
Collecting django<3,>=2.1.6 (from -r requirements.txt (line 2))
Using cached https://files.pythonhosted.org/packages/65/4a/3d3f05ff8cb284cca565adb8b704b3094b0810ae2b5925c6e30e604400f7/Django-2.2.24-py3-none-any.whl
Collecting djangorestframework==3.9.1 (from -r requirements.txt (line 3))
Using cached https://files.pythonhosted.org/packages/ef/13/0f394111124e0242bf3052c5578974e88e62e3715f0daf76b7c987fc6705/djangorestframework-3.9.1-py2.py3-none-any.whl
Collecting djangorestframework-bulk<1,>=0.2.1 (from -r requirements.txt (line 4))
Using cached https://files.pythonhosted.org/packages/32/f8/79fd8c1919fd1e033eedc04fea3396e978eb20c9cda49a0c538e9c5d8127/djangorestframework-bulk-0.2.1.tar.gz
Collecting django-cors-headers<3,>=2.4.0 (from -r requirements.txt (line 5))
Using cached https://files.pythonhosted.org/packages/83/7f/96fa0dc138d4aab23bcbcb312df31ca63fb34f643805f02dddf9e460c648/django_cors_headers-2.5.3-py2.py3-none-any.whl
Collecting django-filter>=1.1.0 (from -r requirements.txt (line 6))
Using cached https://files.pythonhosted.org/packages/71/2b/b2fe483c3095b6222725dd05f9ad9e6ed6cb7347c154fdbd80238d36f1a8/django_filter-2.4.0-py3-none-any.whl
Collecting psycopg2-binary<3,>=2.7.3.1 (from -r requirements.txt (line 9))
Using cached https://files.pythonhosted.org/packages/14/65/223a5b4146b1d5d5ab66f16ef194916a1ed9720da1f118d7bfb60b8f2bea/psycopg2-binary-2.9.1.tar.gz
Complete output from command python setup.py egg_info:
running egg_info
creating pip-egg-info/psycopg2_binary.egg-info
writing pip-egg-info/psycopg2_binary.egg-info/PKG-INFO
writing dependency_links to pip-egg-info/psycopg2_binary.egg-info/dependency_links.txt
writing top-level names to pip-egg-info/psycopg2_binary.egg-info/top_level.txt
writing manifest file 'pip-egg-info/psycopg2_binary.egg-info/SOURCES.txt'

> Error: pg_config executable not found.

> pg_config is required to build psycopg2 from source.  Please add the directory

> containing pg_config to the $PATH or specify the full executable path with the

option:
python setup.py build_ext --pg-config /path/to/pg_config build ...
or with the pg_config option in 'setup.cfg'.
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.

> For further information please check the 'doc/src/install.rst' file (also at

<https://www.psycopg.org/docs/install.html>).
----------------------------------------

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8i9wzot4/psycopg2-binary/
> You are using pip version 9.0.3, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Build failed
ERROR: An error occurred: non-zero (13) exit code from bcgovimages/von-image:py36-1.7-ew-1-s2i

Tried installing the missing psycopg2-binary by 
`pip install psycopg2-binary`
Same error persists. 

Is it that package installation has to be bundled as part of the docker image?

**Comment by WadeBarnes** [comment]
@stoicangelo, [bcgov/TheOrgBook](https://github.com/bcgov/TheOrgBook) project has been retired and archived.  It has been replaced by:
- [bcgov/aries-vcr](https://github.com/bcgov/aries-vcr) for the api, backend, storage, and agent(s).
- [bcgov/orgbook-bc-client](https://github.com/bcgov/orgbook-bc-client) for the front-end, which is built from [bcgov/aries-vcr-client](https://github.com/bcgov/aries-vcr-client).  This frontend will soon be replaced with [bcgov/orgbook-bc-client-vue](https://github.com/bcgov/orgbook-bc-client-vue)

Both have Docker `./manage` scripts, so you can spin them up in the same way you were trying to spin up `TheOrgBook`.

**Comment by stoicangelo** [comment]
@WadeBarnes  thank you so much for the directions. Excited to try them out.
