### ISSUE TITLE
credential_id is missing from the responses of fetch credential exchange record

### ISSUE THREAD

**Issue by SurenAyer** [bcgov/von-network#154]
The GET API call to fetching credential exchange record is missing credential_id attribute.
Because of this the holder is not able to store the credential to the wallet as credential_id is one of the mandatory attribute.
500 internal server is coming if I provide a blank value for credential_id attribute.

**Comment by WadeBarnes** [comment]
@SurenAyer, this does not sound like a `von-network` issue, can you confirm by providing some additional details on what you and doing and the steps to reproduce the issue?

**Comment by SurenAyer** [comment]
@WadeBarnes Sorry for that.....I was supposed to raise this issue in https://github.com/hyperledger/aries-cloudagent-python, mistakenly raised here.. please ignore
