### ISSUE TITLE
Startup fails

### ISSUE THREAD

**Issue by cnokello** [bcgov/von-network#158]
Running 

`./manage start` 

fails with this exception:

`Unable to parse logging level: compose`. 

This might be related to a recent change in docker-compose; https://github.com/docker/compose-cli/issues/1891. 

Environment: Latest code. Windows OS.

**Comment by cnokello** [comment]
I was able resolve the issue by following the recommended workaround in the above post:

` Unchecking the box for Use Docker Compose v2 under Experimental Features`

**Comment by happylancer** [comment]
[To disable Docker Compose V2 using the CLI, run:](https://docs.docker.com/compose/cli-command/)
docker-compose disable-v2
