### ISSUE TITLE
"Loading status" on "Validator Node Status" dashboard when node(s) stopped.

### ISSUE THREAD

**Issue by Aberasturi** [bcgov/von-network#160]
When we start VON-NETWORK and we check Ledger Browser we can see all the nodes up and running

![loading_satus_01](https://user-images.githubusercontent.com/39151755/128471073-0cbacf48-b7ae-4a71-b413-0ffb686f855a.png)

If we stop some of the Nodes Ledger Browser "Validator Node Status" doesn't show the other nodes status showing the message "Loading status".

![loading_satus_02](https://user-images.githubusercontent.com/39151755/128471076-97d159f4-63a2-4033-a63d-520840612241.png)

On ledger browser logs we get the error at "File "/home/indy/server/anchor.py", line 631, in validator_info" because "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".

```
reply = json.loads(node_data[node])
```

When `ledger get-validator-info` transaction is launched, on stopped nodes we haven't a "REPLY" (in json format) but "timeout" (string). For example:

```
"Node4":"timeout"
```

We solved the problem catching the exception and letting the not reachable nodes (timeouted) out of the response.

From

```
reply = json.loads(node_data[node])
```

To

```
  try:
      reply = json.loads(node_data[node])
      if "result" not in reply:
         continue
      data = reply["result"].get("data")
      data["Node_info"]["Name"] = node
      ret.append(data)
  # Some of the nodes a not reachable.
  except json.decoder.JSONDecodeError:
      continue
```

Now if we refresh Ledger Browser and we wait until `get-validator-info`  transcation finish, we can see the other started nodes.

![loading_satus_03](https://user-images.githubusercontent.com/39151755/128471078-ddd92380-d7af-4d54-b932-5617dead1d81.png)

**How to reproduce the problem:**

1. Start VON-NETWORK
2. Check Ledger Browser (http://localhost:9000)
3. Stop one of the Nodes.
```
docker stop [von_node2_1, von_node2_1, von_node3_1, von_node4_1
or
docker-compose stop [node1, node2, node3, node4]
```
4. Refresh Ledger Browser

**Comment by WadeBarnes** [comment]
@Aberasturi, Could you submit a PR with the fix?

**Comment by WadeBarnes** [comment]
Fixed with https://github.com/bcgov/von-network/pull/164
