### ISSUE TITLE
"Unable to parse logging level:" 

### ISSUE THREAD

**Issue by bmaier** [bcgov/von-network#161]
Command  ./manage start  result in following error:
"Unable to parse logging level:"

Docker Compose version: v2.0.0-beta.6

The current re-implementation of docker-compose doesn’t support  the flag --log-level.
https://github.com/docker/compose-cli/issues/1891
Docker don’t  accept this as a bug and will in future also available in RC.

Workaround:  removing  --log-level from ./manage script

**Comment by WadeBarnes** [comment]
@bmaier, Would you like to submit a PR with a fix?  It appears the proper fix would be to use the `docker compose` syntax and move the `--log-level` flag to the appropriate level.

For example:
```bash
  start|up)
      initEnv "$@"
      install_taa
      docker-compose \
        --log-level ERROR up \
        -d webserver node1 node2 node3 node4
      wait_for_ledger
      logs
      echo 'Want to see the scrolling container logs? Run "./manage logs"'
    ;;
```
would become
```bash
  start|up)
      initEnv "$@"
      install_taa
      docker --log-level error \
        compose up \
        -d webserver node1 node2 node3 node4
      wait_for_ledger
      logs
      echo 'Want to see the scrolling container logs? Run "./manage logs"'
    ;;
```
