### ISSUE TITLE
Compilation fails on the latest version

### ISSUE THREAD

**Issue by kthomas-digicat** [bcgov/von-network#167]
Hi, the compilation fails when I compile the latest version:

` => ERROR [7/8] RUN tar -xzf ./bin/sst_dump.tar.gz -C ./bin     && rm ./bin/sst_dump.tar.gz     && chmod +x ./bin/sst_dump                     0.3s
------
 > [7/8] RUN tar -xzf ./bin/sst_dump.tar.gz -C ./bin     && rm ./bin/sst_dump.tar.gz     && chmod +x ./bin/sst_dump:
#11 0.273 
#11 0.273 gzip: stdin: invalid compressed data--format violated
#11 0.274 tar: Unexpected EOF in archive
#11 0.274 tar: Unexpected EOF in archive
#11 0.274 tar: Error is not recoverable: exiting now
------
executor failed running [/bin/sh -c tar -xzf ./bin/sst_dump.tar.gz -C ./bin     && rm ./bin/sst_dump.tar.gz     && chmod +x ./bin/sst_dump]: exit code: 2`

**Comment by WadeBarnes** [comment]
Fix for this is here; https://github.com/bcgov/von-network/pull/168

**Comment by WadeBarnes** [comment]
The associated fix has been merged, closing this issue.

**Comment by kthomas-digicat** [comment]
Thank you so much for your timely fix Wade, really appreciate your help
