### ISSUE TITLE
config the node IP

### ISSUE THREAD

**Issue by zhangbobo2023** [bcgov/von-network#174]
How to config the node/pool IP when start，thanks

**Comment by WadeBarnes** [comment]
From `./manage -h`
```
  Usage: ./manage [command] [--logs] [options]

  Commands:
  ...
  start | up - Starts all containers
       You can include a '--wait' parameter which will wait until the ledger is active
       You can include a '--taa-sample' parameter which will install the sample Transaction Authorisation Agreement
        files into the ledger. Alternatively you can create your own config/aml.json and config/taa.json files which
        will get installed into the ledger at start (see config/sample_aml.json and config/sample_taa.json for format)
       When using the '--logs' option, use ctrl-c to exit logging. Use "down" or "stop" to stop the run.
        Examples:
        ./manage start
        ./manage start --logs
        ./manage start <ip_proxy_1>,<ip_proxy_2>,<ip_proxy_3>,<ip_proxy_4> &
        ./manage start --wait --logs
        ./manage start --taa-sample
```

From [Running the Network on a VPS - Step 5](https://github.com/bcgov/von-network#running-the-network-on-a-vps):
```
# This command requires the publicly accessible ip address of the machine `public_ip_address`
# WEB_SERVER_HOST_PORT maps the docker service port to a public port on the machine
# LEDGER_INSTANCE_NAME sets the display name of the ledger on the page headers.
./manage start public_ip_address WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=My Ledger" &
```

For example the start command for http://test.bcovrin.vonx.io/ is:
```
./manage start 138.197.138.255 WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=BCovrin Test" "INFO_SITE_TEXT=vonx.io" "INFO_SITE_URL=https://vonx.io/"
```

**Comment by zhangbobo2023** [comment]
> From `./manage -h`
> 
> ```
>   Usage: ./manage [command] [--logs] [options]
> 
>   Commands:
>   ...
>   start | up - Starts all containers
>        You can include a '--wait' parameter which will wait until the ledger is active
>        You can include a '--taa-sample' parameter which will install the sample Transaction Authorisation Agreement
>         files into the ledger. Alternatively you can create your own config/aml.json and config/taa.json files which
>         will get installed into the ledger at start (see config/sample_aml.json and config/sample_taa.json for format)
>        When using the '--logs' option, use ctrl-c to exit logging. Use "down" or "stop" to stop the run.
>         Examples:
>         ./manage start
>         ./manage start --logs
>         ./manage start <ip_proxy_1>,<ip_proxy_2>,<ip_proxy_3>,<ip_proxy_4> &
>         ./manage start --wait --logs
>         ./manage start --taa-sample
> ```
> 
> From [Running the Network on a VPS - Step 5](https://github.com/bcgov/von-network#running-the-network-on-a-vps):
> 
> ```
> # This command requires the publicly accessible ip address of the machine `public_ip_address`
> # WEB_SERVER_HOST_PORT maps the docker service port to a public port on the machine
> # LEDGER_INSTANCE_NAME sets the display name of the ledger on the page headers.
> ./manage start public_ip_address WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=My Ledger" &
> ```
> 
> For example, the start command for http://test.bcovrin.vonx.io/ is:
> 
> ```
> ./manage start 138.197.138.255 WEB_SERVER_HOST_PORT=80 "LEDGER_INSTANCE_NAME=BCovrin Test" "INFO_SITE_TEXT=vonx.io" "INFO_SITE_URL=https://vonx.io/"
> ```
