### ISSUE TITLE
config the node IP

### ISSUE THREAD

**Issue by zhangbobo2023** [bcgov/von-network#176]
run the repo on ubuntu env，

first machine is 47.108.65.119， down load  von-network（indy-node version is 1.12.4），and start the cmd：

./manage build
./manage start 47.108.65.119,47.108.65.119,47.108.65.119,47.108.65.119

second machine is 47.108.93.62，down load ACA-Py（version is 0.7.0），and start the cmd：

cd aries-cloudagent-python/demo
LEDGER_URL=http://47.108.65.119:9000/  ./run_demo faber  --aip 10

but failed，error  as follows ：

+++++++++++++++++++++++++++++++++++++++++++++++++++++

root@iZ2vcekg07cyl1x0potmotZ:~/aries-cloudagent-python/demo# LEDGER_URL=http://47.108.65.119:9000/  ./run_demo faber --aip 10
Preparing agent image...
sha256:452aa1b4af9acbbccdbfe5b6f840a82fae49fe172d68cc0e99859324c514f000
Trying to detect ngrok service endpoint
jq not found
172.24.205.86
Starting [faber] agent with args [--port 8020 --aip 10]
Initializing demo agent faber with AIP 10 and credential type indy

#1 Provision an agent and wallet, get back configuration details
Faber      | Registering faber.agent ...
Shutting down agent ...
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/indy/demo/runners/faber.py", line 584, in <module>
    asyncio.get_event_loop().run_until_complete(main(args))
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/home/indy/demo/runners/faber.py", line 104, in main
    schema_attrs=faber_schema_attrs,
  File "/home/indy/demo/runners/agent_container.py", line 619, in initialize
    await self.agent.register_did(cred_type=self.cred_type)
  File "/home/indy/demo/runners/support/agent.py", line 387, in register_did
    f"Error registering DID, response code {resp.status}"
Exception: Error registering DID, response code 404

and I have test that if run ACA-Py demo on  first machine(together with von-network), no error occured。so why and how to solve，thanks。

**Comment by WadeBarnes** [comment]
As far as starting `von-network` to expose it on the IP of the first machine running `./manage start 47.108.65.119` would be sufficient.  You don't need to list the same IP all four times.

As far as the rest of the question goes, that's a question that should rally be asked over on [hyperledger/aries-cloudagent-python](https://github.com/hyperledger/aries-cloudagent-python/issues).

Can you browse to the ledger from the second machine?
When you run the demo on the same machine hosting `von-network`, are you using the same or a different command to start the demo?
Have you tried running the command without the trailing `/` on the ledger URL?  For example; `LEDGER_URL=http://47.108.65.119:9000`

**Comment by zhangbobo2023** [comment]
> As far as starting `von-network` to expose it on the IP of the first machine running `./manage start 47.108.65.119` would be sufficient. You don't need to list the same IP all four times.
> 
> As far as the rest of the question goes, that's a question that should really be asked over on [hyperledger/aries-cloudagent-python](https://github.com/hyperledger/aries-cloudagent-python/issues).
> 
> Can you browse to the ledger from the second machine?
> When you run the demo on the same machine hosting `von-network`, are you using the same or a different command to start the demo?
> Have you tried running the command without the trailing `/` on the ledger URL? For example; `LEDGER_URL=http://47.108.65.119:9000`


Thanks，problem has solved。
