### ISSUE TITLE
ACA-Py can't publish a private DID to Von-network

### ISSUE THREAD

**Issue by yunxi-zhang** [bcgov/von-network#186]
Hello, I've upgraded my local VON-network to its latest version. After turning on multi-tenancy feature in ACA-Py, I can't publish a private DID to VON-network, which was not an issue when I used an old version of VON-network. Below shows the steps of how to reproduce the issue.

**Environment:**
ACA-Py version: 0.6.0

Step 1: Turn on the VON-network by using the `./manage up `command.
Step 2: Run an ACA-Py agent without giving a **seed** flag as parameters.
Step 3: Call the API "/multitenancy/wallet" to create a sub wallet in the agent.
Step 4: Call the API "/wallet/did" for twice and verify two private DIDs have been created successfully.
![image](https://user-images.githubusercontent.com/16185797/139274465-b4fd8575-82ed-43c4-9977-e7dd23c61f1b.png)
Step 5: Call the API "wallet/did/public?did=Cv3gHFy7PXbF5agXhv49Hh" to publish a DID, and an error is returned.
![image](https://user-images.githubusercontent.com/16185797/139274734-cbfcd64c-5808-45cb-96bb-89a2dbf703bf.png)

Could anyone help here? Thanks!

**Comment by WadeBarnes** [comment]
This issue is being discussed over here; https://github.com/hyperledger/aries-cloudagent-python/issues/1460

**Comment by yunxi-zhang** [comment]
Sure, happy to close this ticket and use the other one as the main one.
