### ISSUE TITLE
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

### ISSUE THREAD

**Issue by edbkei** [bcgov/von-network#187]
Hi,

I´ve got a VM ( Ubuntu 20.04.3 LTS) from a Openstack cloud mantained by a University.
I´ve requested to open several ports (80, 8080, 443, etc), and I´ve installed von-network, hyperledger aries, docker, python, pip, etc.

I´ve started local ledger and tried to run agent faber.
cd von-network
./manage up
cd ../aries-cloudagent-python/demo
./run_demo faber

and I got the following error:

ubuntu@eduardoito:~/dissertation$ cd aries-cloudagent-python/demo
ubuntu@eduardoito:~/dissertation/aries-cloudagent-python/demo$ ./run_demo faber
Preparing agent image...
Sending build context to Docker daemon  16.96MB
Step 1/18 : FROM bcgovimages/von-image:py36-1.15-1
 ---> 1624dd24c5b9
Step 2/18 : ENV ENABLE_PTVSD 0
 ---> Using cache
 ---> 54746fe0d088
Step 3/18 : ENV ENABLE_PYDEVD_PYCHARM 0
 ---> Using cache
 ---> bb728f0a2a56
Step 4/18 : ENV PYDEVD_PYCHARM_HOST "host.docker.internal"
 ---> Using cache
 ---> d5dbef0ad6a9
Step 5/18 : RUN mkdir bin && curl -L -o bin/jq  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 &&   chmod ug+x bin/jq
 ---> Running in 938838243bb9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:01 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
The command '/bin/sh -c mkdir bin && curl -L -o bin/jq  https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 &&   chmod ug+x bin/jq' returned a non-zero code: 35
ubuntu@eduardoito:~/dissertation/aries-cloudagent-python/demo$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

In my laptop (with same OS), this not happens, it runs OK.

Please, if you have an idea of what it could be, I appreciate.

Thanks

Eduardo

**Comment by WadeBarnes** [comment]
The issue you are encountering is in the `aca-py` build, it's not a `von-network` issue.  Regardless, it looks like your University hosted VM is sitting behind a proxy and you'll have to configure the proxy settings in `git`.  If you google "OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443" you will find the guidance you need.

**Comment by edbkei** [comment]
Sorry for openning a new issue in the unproper forum, you may close this issue. And thanks for advicing me about the proxy. I will address this issue for my personnel.
