### ISSUE TITLE
Error initializing pool ledger

### ISSUE THREAD

**Issue by devika-vinay** [bcgov/von-network#192]
I'm trying to start von-network through git bash on windows 11, but i keep getting "error initializing pool ledger" despite following the instructions to clear image cache in docker, ./manage rm and other such suggestions. What do I do next?

![image](https://user-images.githubusercontent.com/50499237/150747168-c81e9ed8-3af7-4420-9bea-3946042928ce.png)
![image](https://user-images.githubusercontent.com/50499237/150747949-31dd4a36-89a1-441d-bbe5-dfdc0dbf5f7d.png)

**Comment by WadeBarnes** [comment]
Make sure you are using the latest version of `von-network`.  Also, please provide details of what commands you are running, and provide the complete log output in text format for review.

Here is a screenshot of `von-network` running on Windows 11 using the following commands:

Clear any existing containers and volumes (reset `von-network`)
```
./manage rm
```

Rebuild the image to make sure you're using the latest code
```
./manage rebuild
```

Start `von-network` with logging
```
./manage start --logs
```

![image](https://user-images.githubusercontent.com/10504350/150786204-cfd5b63e-6a8c-4d7f-9979-345cb8c57599.png)

**Comment by WadeBarnes** [comment]
The webserver is trying to connect to the node pool before the pool has finished initializing.  This can happen on first startup.  In this case a `./manage stop` (NOT `down` or `rm`), followed by a `./manage start` will typically solve the issue as the pool will have already been setup on the  first start-up.  Depending on how loaded your machine is you may always experience this startup issue.  In this case you can extend the sleep time on this line https://github.com/bcgov/von-network/blob/main/docker-compose.yml#L25.  You could start by trying 20 or 30 seconds.

**Comment by LouBa310** [comment]
Heyy, I'm experiencing the same issue. I've already tried the solutions from above but there isn't any noticable change. What else can I try to get the network running? 
Thanks in advance :)
