### ISSUE TITLE
Permission Denied on executing Indy-CLI scripts

### ISSUE THREAD

**Issue by vpapanchev** [bcgov/von-network#194]
Hi,

I am following the [**Using the containerized indy-cli**](https://github.com/bcgov/von-network/blob/main/docs/Indy-CLI.md) tutorial. When I run ```./manage indy-cli create-wallet walletName=test_1``` I get the following  error:
```
papanchev@papanchev-Inspiron-5559:~/ssi-workspace/von2/von-network$ ./manage indy-cli create-wallet walletName=test_wallet_1

Using: docker-compose --log-level ERROR

Creating von_client_run ... done
./scripts/manage: line 129: ./cli-scripts/create-wallet.run: Permission denied
ERROR: 1
```

Has someone encountered this in the past?

**Comment by vpapanchev** [comment]
This was it!
It is also worth mentioning (for the less experienced developers like myself) to also rebuild the docker containers after updating the permissions...

Thank you @WadeBarnes

**Comment by alperari** [comment]
@vpapanchev it's been a long time since the issue is closed but how did you manage to give permission to `indy` user in your container, to be able to write in `./cli-scripts` in your host machine?

In my case, removing the if-check in `manage` solved it:
```sh
function setFolderReadWriteAll() {
  folder=${1}
  permissions=$(stat ${STAT_OPS} ${folder})

  if [[ "${permissions:0-1}" != 5 ]]; then          # Removed this 👈
    echo "Setting ${folder} to read/write for all users ..."
    chmod a+rws ${folder}
  fi
}
```

**Comment by WadeBarnes** [comment]
@alperari, the code you pointed out is meant to check the permission on the `cli-scripts`, for one, and ensure all users can read and write to the folder `a+rw`, and the permissions on the folder propagate to any files written there, the `s` part.  The fact that the `chmod a+rws ${folder}` line was not being executed on your system until you removed the check indicates the check is not working correctly on your machine.  What OS are you using.  I had tested this on Windows and MAC.

To be clear permissions are never explicitly granted to the `indy` user, they are granted to all (other) users.

**Comment by alperari** [comment]
@WadeBarnes thank your for your comment.
You are right, that part is never being executed until i remove the if-check.

And when i check the permissions on the folder, i see `755`.
But correct me if i'm wrong, isn't 5 means read + execute? So `indy` user is actually never able to write on it?

I am using WSL2 for docker-related developments.

**Comment by WadeBarnes** [comment]
Thanks for the update and feedback.  I'll do some more testing on Ubuntu 22.04 when I have a moment.

**Comment by WadeBarnes** [comment]
@alperari, I did some additional testing.  You were correct, as expected.  The fix for your issue is here; https://github.com/bcgov/von-network/pull/290
