### ISSUE TITLE
ledger browser empty after start

### ISSUE THREAD

**Issue by jweko** [bcgov/von-network#195]
I cloned the von-network from git and after ./manage build I started with ./manage start --logs
If I try to open the ledger browser it looks like this

![emptyLedgerBrowser](https://user-images.githubusercontent.com/86103606/158663773-aaf3d79d-79d7-413d-81c7-f6a829c3aafe.PNG)

It shows a blank page, while /genesis shows some output. It does not matter how long I wait after the start. 

**Log:**
[VonNetworkLog_1.log](https://github.com/bcgov/von-network/files/8268747/VonNetworkLog_1.log)

=============================
**Environment:**
Operating System: Ubuntu 20.04.3 LTS (it's an openstack vm)
Kernel: Linux 5.4.0-97-generic
Architecture: x86-64

Docker Version:
Client: Docker Engine - Community
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:07:51 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:44 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

=============================
**Changes:** 
-tried to enlarge the sleep in the docker-compose.yml -> no difference 
-tried to use a different port by starting with WEB_SERVER_HOST_PORT=8080 -> no difference 
-tried also using a window openstack machine with wsl2 -> same behavior 
-tried to start/stop multiple times
-also tried stop, rm, start
-also tried down, start followed by stop/start mult. times
-also tried rm, rebuild, start 

Any idea why the browser does not show any content? Any help or hint would be appreciated. Thx!

**Comment by WadeBarnes** [comment]
Have you tried using a different browser?

Could you start `von-network` and then run the following to capture the logs from the web server and post them:
```
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-von}"
docker-compose logs -f  webserver
```

**Comment by jweko** [comment]
Thanks for your quick response.
As we now figured out it was an internet access issue. The ledger browser tries to load some java script stuff and so on from the internet. But my machine has only limited internet access and no access to those urls so to load the ledger browser failed. 

![emptyLedgerBrowser2](https://user-images.githubusercontent.com/86103606/158775842-5de1d6e4-6888-4646-a691-a91bac87efa7.PNG)
