### ISSUE TITLE
Remove dependency on bind mounts in docker-compose

### ISSUE THREAD

**Issue by tdiesler** [bcgov/von-network#223]
Currently there are several volume references to bind mounts like this ...

```
      - ./config:/home/indy/config
      - ./server:/home/indy/server
```

These could be replaced by a build step in the compose file

**Comment by WadeBarnes** [comment]
Refer to https://github.com/bcgov/von-network/pull/224#issuecomment-1111452125 for information on the intended purpose of the bind mounts.

**Comment by WadeBarnes** [comment]
Closing this since the associated PR has been closed too.
