### ISSUE TITLE
Error initializing pool ledger after adding new node 5,6,7

### ISSUE THREAD

**Issue by akshaykurhekar** [bcgov/von-network#227]
Hi,

all 7 nodes are running but ledger is not showing node on localhost:9000
![Screenshot from 2022-05-25 11-57-56](https://user-images.githubusercontent.com/55475959/170195038-8d606dd6-c6cb-41b5-9b4e-28cef8f4f23d.png)

$ docker ps
![Screenshot from 2022-05-25 12-00-01](https://user-images.githubusercontent.com/55475959/170195373-274a9653-90ae-4db1-adb6-b0764a735ac1.png)

to add new node I used first method from here:
https://github.com/bcgov/von-network/blob/main/docs/AddNewNode.md#2-register-new-nodes-in-ledger

 to fix issue I tryed 

./manage rebuild 
./manage start 

but no luck pls help me on this.

**Comment by WadeBarnes** [comment]
That error is from the webserver (ledger browser) and typically appears when it starts before all the nodes are ready.  You can try adjusting the timeout to delay it's startup; https://github.com/bcgov/von-network/blob/main/docker-compose.yml#L25

**Comment by WadeBarnes** [comment]
A quick reminder, `von-network` is a provisional tool, it is not intended for use as a production grade network.  If you're looking for a production grade network, there are other resources I could point you at.

**Comment by akshaykurhekar** [comment]
Hi, wadeBarnes 
Thank you for help
can you pls point few resources for production grade network for identity management.

**Comment by akshaykurhekar** [comment]
Thanks WadeBarnes

adjusting the timeout to delay it's startup; https://github.com/bcgov/von-network/blob/main/docker-compose.yml#L25

this works for me.

pls, suggest me resources for a production-grade network.

![Screenshot from 2022-06-01 11-06-43](https://user-images.githubusercontent.com/55475959/171335212-9e573e03-42ee-417a-a78a-915abbde609c.png)

**Comment by akshaykurhekar** [comment]
Thanks, WadeBarnes

for helping me with resources.
