### ISSUE TITLE
Dev Ledger Indy Network does not show new transactions

### ISSUE THREAD

**Issue by pasquale95** [bcgov/von-network#228]
When I try to look at the ledger state (Domain) for the ledger at http://dev.greenlight.bcovrin.vonx.io/ I see the latest transaction at the 3rd July 2022, while I am constantly creating new transactions (as nym, schema_def and credential_def) with my aca-py agent.
It seems as the ledger scan does not work anymore. Can you please check if it's the case?
Thank you.

**Comment by WadeBarnes** [comment]
I've restated the browser.  Give it some time to refresh, and then check again.
