### ISSUE TITLE
createPoolLedgerConfig error:  PoolLedgerConfigAlreadyExistsError

### ISSUE THREAD

**Issue by zhb001** [bcgov/von-network#251]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/116326312/224278521-364c1530-d225-4a55-aef2-aeeb8609b5d2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/116326312/224279022-74f6ca68-b273-43e0-8db0-d5220d21d64a.png">

**Comment by zhb001** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/116326312/224279363-516cd29a-7d2c-4bf1-bb2a-cc08b7ce5bf8.png">

**Comment by zhb001** [comment]
Can someone answer this question? Sorry, my English is not very good. The following content comes from machine translation. I used nodejs demo from indy-sdk, and got the following error. I don't know where I was wrong. I used vps to run von. webserve can run normally, but it will report an error if accessed through demo

**Comment by zhb001** [comment]
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/116326312/224280404-8d853439-0098-4c23-82fd-891fb162f80d.png">

**Comment by WadeBarnes** [comment]
https://github.com/hyperledger/indy-sdk/issues/2585
