### ISSUE TITLE
Cannot modify seed number of trustee

### ISSUE THREAD

**Issue by darapich92** [bcgov/von-network#253]
Hello everyone, I have a problem when I want to modify seed number of trustee in the `manage.sh`, I got an error of each node `error: 'client request invalid: could not authenticate, verkey for UnB4FgtLv1M9BpDP3iuTfn cannot be found' `. Could you help me to solve this problem?

Thank you very much.

**Comment by WadeBarnes** [comment]
Please provide details of the steps that lead up to your error, as well as some background of what you're trying to accomplish.

**Comment by darapich92** [comment]
Hi @WadeBarnes, I changed the `LEDGER_SEED=${LEDGER_SEED:-000000000000000000000000Trustee1}` --> `LEDGER_SEED=${LEDGER_SEED:-000000000000000000000001Trustee1}` in the `manage.sh` in the von-network. As expected, it should work fine but when I execute the script containing new seed number, the 4 nodes in the web-server cannot be online and got the error messages as I mentioned before. I raise a question, should I change code somewhere else more to make von-network?

**Comment by WadeBarnes** [comment]
Changing `LEDGER_SEED` only changes the DID used by the network browser to connect to the nodes in the pool,  It is used to connect the ledger browser to other networks.  It DOES NOT affect the DID of the primary trustee on the network.  von-network uses scripts within indy-node and indy-plenum to generate a test network.  The SEED and therefore the DID of the primary trustee for the network is hard coded for the test network at the indy-plenum level.

**Comment by darapich92** [comment]
Thank you @WadeBarnes for your answer. So, could you tell me why we need LEDGER_SEED when we execute `./manage up`?

**Comment by WadeBarnes** [comment]
By default you don't need to specify `LEDGER_SEED` when running von-network, unless you're trying to connect to a different ledger, one that was not created by von-network in he first place.  See my previous comment.

**Comment by WadeBarnes** [comment]
Have a look at the [auth_rules](https://github.com/hyperledger/indy-node/blob/main/docs/source/auth_rules.md) for indy-node.  It will give you an idea on what the various roles and what they can do.

**Comment by WadeBarnes** [comment]
Closed, since the original question was answered.
