### ISSUE TITLE
BCovrin Test Browser filtering/paging failing due to a weird transaction

### ISSUE THREAD

**Issue by swcurran** [bcgov/von-network#256]
See the conversation here: https://chat.developer.gov.bc.ca/group/dcs-bcgovteam?msg=MnaLeJ8hkMku2sadz -- I'll copy it into a comment below so others can see it.

The issue is that transaction [691769](http://test.bcovrin.vonx.io/ledger/domain/691769) has some weird data in it, and that data blows up the BCovrin Test Browser.

An update should be made to the Browser to be tolerant of this type of issue and deployed so that we can use the browser with BCovrin Test so that we get back full functionality.

We could transition to using IndyScan for BCovrin Test, but I think there is value in keeping the von-network browser for other use cases -- e.g. a quick'n'dirty local test browser.

**Comment by swcurran** [comment]
### Conversation on RocketChat about this issue:

Andrew Whitehead @andrew.whitehead
4:08 PM
[test.bcovrin](https://test.bcovrin/) is getting a 500 error when filtering the ledger browser 😞

Emiliano Sune @esune
4:16 PM
yeah, it looks like it's having trouble dealing with the amount of data on the ledger
March 17, 2023

Wade Barnes @wade.barnes
5:52 AM
I propose we stand up an IndyScan instance for the BCovrin networks. The built in browser has been having great difficulty with the volume of data on BCovrin Test.

Wade Barnes @wade.barnes
6:00 AM
It might actually be having an issue with some of the data on the ledger.

Wade Barnes @wade.barnes
6:01 AM
ErrorLog.txt

TXT
[ErrorLog.txt](https://chat.developer.gov.bc.ca/file-upload/BtZ7MkozPxcxiEtYZ/ErrorLog.txt)

Wade Barnes @wade.barnes
6:05 AM
Perhaps a cleaner error log
ErrorLog2.txt

TXT
[ErrorLog2.txt](https://chat.developer.gov.bc.ca/file-upload/5uHfr9qNAKzZaxzrp/ErrorLog2.txt)
Andrew Whitehead, would it be worth purging the cache database in case it got corrupted?

Andrew Whitehead @andrew.whitehead
9:22 AM
It looks more like a bad assumption about the format of the data to me

Emiliano Sune @esune
9:23 AM
did the data structures change at some point in time?

Andrew Whitehead @andrew.whitehead
9:23 AM

```
result["data"] = " ".join(txn["data"]["data"]["primary"]["r"].keys())
KeyError: 'r'
```

Not sure what 'r' is there but it could get left out if empty. Or it's an invalid record but the ledger didn't check that

Emiliano Sune @esune
9:37 AM
assuming the data structures did not suddenly change the invalid record option seems possible - and a bit concerning?

Andrew Whitehead @andrew.whitehead
9:48 AM
http://test.bcovrin.vonx.io/ledger/domain/691769
It looks like that cred def txn might be malformed:

```
      "txn": {
        "data": {
          "data": {
            "primary": {
              "primary": {
```

The data/data is normal, but primary/primary is not afaik

Wade Barnes @wade.barnes
9:51 AM
Yeah, primary/primary does not look right.

Stephen Curran @swcurran
Owner
12:56 PM
So we need a ticket on von-network for the server to handle this weird type of transaction?

Emiliano Sune @esune
12:57 PM
It would be interesting to understand HOW a malformed transaction made it to the ledger - I did not think that was possible, or easy at least

Andrew Whitehead @andrew.whitehead
1:36 PM
I think the validation of the objects in indy-node is a bit limited, it doesn't really need to know that every credential definition is valid (it would cause problems if another signature type was added for example). The browser should probably just be tolerant of invalid records

Emiliano Sune @esune
2:01 PM
This makes a lot more sense (to me) now, thank you!

**Comment by WadeBarnes** [comment]
The updated version of von-network has been deployed to all environments.  The issue with the record on http://test.bcovrin.vonx.io/ has been resolved.  The record can now be processed without error:
![image](https://github.com/bcgov/von-network/assets/10504350/d4a2dcb0-c8ba-43a3-b476-b62fa9cb373b)
