### ISSUE TITLE
Unable to run the ./manage command

### ISSUE THREAD

**Issue by sudddy** [bcgov/von-network#258]
Hello all, 
I'm using m1 pro chip and trying to setup the local environment. Unfortunately, i couldn't resolve the below error. Some help over here would be greatly appreciated. Thanks. 

```
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
Setting ./tmp to read/write for all users ...
chmod: Invalid file mode: ./tmp
stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
Setting ./cli-scripts to read/write for all users ...
chmod: Invalid file mode: ./cli-scripts
```

**Comment by WadeBarnes** [comment]
The issue is this code:
https://github.com/bcgov/von-network/blob/eb427b3badf403d0960eae17241d97664e5bf76c/manage#L844-L852

Unfortunately I do not have a MAC to test this on.  Obviously the syntax is a bit different on the MAC.

**Comment by sudddy** [comment]
I guess it's because of the Mac OS version (Monterey). (Not 100% sure though)
I tried running it on the latest version - Ventura  - Even though I had the same error popping out in this version but it spun up the image. 

Thanks, @WadeBarnes
