### ISSUE TITLE
Using local von-network with aries bifold wallet 

### ISSUE THREAD

**Issue by Sshovon** [bcgov/von-network#270]
I want to use the locally initiated ledger in the aries bifold wallet. I have tested the local von network with Alice and Faber agent of Aries cloud agent python. It works fine but when I try to use it with my wallet it doesn't work as expected. I have used ngrok to make port 9000 online. And added that https://ngrok/genesis in the wallet genesis file. But in this setup wallet can't retive did from the ledger we provided. So it seems that our setup is not correct. Can anyone help me out?

**Comment by WadeBarnes** [comment]
@jleach, @amanji, do either of you have any experience using a local instance on von-network with a mobile wallet?

**Comment by amanji** [comment]
I haven’t, but I suspect that the IPs in the genesis block are local which are not reachable from the wallet. Any chance you’d be willing to post your genesis file?

**Comment by Sshovon** [comment]
Yes, the IPs are provided by the docker host of my local machine. Can you please help me by suggesting the steps to make this? Would you like me to use EC2 instance? 
[genesis.txt](https://github.com/bcgov/von-network/files/12036354/genesis.txt)

**Comment by Sshovon** [comment]
I have hosted the von network in an EC2 instance. Here is the [link](100.26.23.213/). Now, when I try to start acapy Faber agent using this ledger, it gives pool timeout but it writes the did of the agent in the ledger. Communication between alice and faber agent works fine with the local von network on my machine. I am attaching the ledger URL that I have used to start faber agent and the error screenshot. 
`LEDGER_URL=http://100.26.23.213 ./run_demo faber`
![Screenshot from 2023-07-13 16-06-04](https://github.com/bcgov/von-network/assets/47460398/9e041a1f-04f1-4e52-afc6-351214d4d699)

**Comment by jleach** [comment]
Is the network reachable? You can use `timeout 5 bash -c "</dev/tcp/100.26.23.213/nnnn"; echo $?` where `nnnn` is the port number the node is listening on. When I try on ports I think you may be using I get `127` which means - nope, not reachable from the internet. Check firewall rules and that you're using the default ports. The IP `20.200.95.22` is for a Candy node and is working as expected.

```console
root@7339f64e0189:/# timeout 5 bash -c "</dev/tcp/20.200.95.22/9702"; echo $?
0
root@7339f64e0189:/# timeout 5 bash -c "</dev/tcp/100.26.23.213/9702"; echo $?
124
root@7339f64e0189:/# timeout 5 bash -c "</dev/tcp/100.26.23.213/9701"; echo $?
124
root@7339f64e0189:/# 
```

**Comment by Sshovon** [comment]
Thank you very much @WadeBarnes  @jleach  @amanji. I have resolved the issue. Thanks again.
