### ISSUE TITLE
Requesting new tagged release

### ISSUE THREAD

**Issue by ff137** [bcgov/von-network#274]
Good day

We're using the von-network in our build/deploy jobs, and currently point to the #main branch, as the previous release (v1.7.2) is almost 2 years old. For maintainability, it'll be better if we could point to a stable release, so just thought I'd post a request here.

Here's the compare of main vs 1.7.2: https://github.com/bcgov/von-network/compare/v1.7.2...main

P.S. Looking through server/requirements.txt, I notice quite a few lines were last touched 4 years ago. Probably worth upgrading (#275) -- but I don't see any tests to ensure there are no breaking changes in the dependencies... 

Additionally, I know it's a different repo, but it has the same maintainers: `indy-vdr` is also due for a new release!

**Comment by WadeBarnes** [comment]
Addressed with https://github.com/bcgov/von-network/releases/tag/v1.8.0

**Comment by ff137** [comment]
@WadeBarnes thanks! 👏
