### ISSUE TITLE
Error response from daemon: pull access denied for von-network-base

### ISSUE THREAD

**Issue by lenrepo** [bcgov/von-network#277]
I tried building a local instance of the Von-network running a git pull of this repository but the ./manage start command would run into error saying " Error response from daemon: pull access denied for von-network-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

I opened the docker-compose.yml and realized it was making reference to von-network-base image which at this point does not exist. I looked into the dockerfile and found a reference to "ghcr.io/bcgov/von-network-base:sha-4599bdff" image, I modified the docker-compose.yml file, replaced all reference to von-network-base with "ghcr.io/bcgov/von-network-base:sha-4599bdff" and this solved my problem. I just thing the docker-compose.yml should be updated to point to the right VON-Network image

**Comment by WadeBarnes** [comment]
Hi @lenrepo, The [documented](https://github.com/bcgov/von-network/blob/main/docs/UsingVONNetwork.md) method to start `von-network` after you've cloned the repository is to run:
```
./manage build
./manage start
```

The `./manage build` command will build the `von-network-base` image from the latest source.

**Comment by lenrepo** [comment]
my bad. I must have missed that, thank you. I will close this issue now.
