### ISSUE TITLE
Changing the exposed ports of the nodes

### ISSUE THREAD

**Issue by GramThanos** [bcgov/von-network#283]
Is there an option to change the exposed ports of the nodes?

I tried to do it by changing the mapping of the ports on the `docker-compose.yml` but the web interface failed to start.
Anyone knows how to solve this?

**Comment by WadeBarnes** [comment]
@GramThanos, Can you provide some more detail regarding what you are trying to accomplish?  It would then be easier to provide guidance or information.

**Comment by GramThanos** [comment]
I am asking if there is an easy way to change the ports the von-nodes are running on (the highlighted ports on the containers on the image):
![image](https://github.com/bcgov/von-network/assets/14858959/36e66693-0101-489a-8ddc-c844fe90e077)

I tried to look around the code and I don't think I there is an option for that (which is fine).
I am not sure how to do it manually, I first tried to only change the mapping of the external ports to the internal ports done by 
https://github.com/bcgov/von-network/blob/main/docker-compose.yml#L85-L92 (I also changed the exposed port for each node), but I don't think this is the correct way to do it.

I can see related port configuration in various places:
[start_node.sh](https://github.com/bcgov/von-network/blob/41a0fd87d14fb5dc8a5b0be5c1c5d5d3ec9e4b7d/scripts/start_node.sh)#L7C18-L7C18
[start_nodes.sh](https://github.com/bcgov/von-network/blob/41a0fd87d14fb5dc8a5b0be5c1c5d5d3ec9e4b7d/scripts/start_nodes.sh)#L6 (defined as variable but not used)
[docker-compose.yml](https://github.com/bcgov/von-network/blob/41a0fd87d14fb5dc8a5b0be5c1c5d5d3ec9e4b7d/docker-compose.yml#L85)

So, my question(s) is "Can I change these ports by changing those 3 files? Is that enough?"

**Comment by WadeBarnes** [comment]
As you've discovered there is no easy way to change the port numbers.  It's a fairly hard coded process that matches and utilizes utilities from `indy-node` to initialize a genesis file meant for a pool of test nodes.  The scripts call `init_genesis.sh` which in turn calls `von_generate_transactions`, which in turn calls [`generate_indy_pool_transactions`](https://github.com/hyperledger/indy-node/blob/main/scripts/generate_indy_pool_transactions).  All of the scripts assume the port numbering starts at `9700` and they do not allow you to pass in a different starting port number.

**Comment by GramThanos** [comment]
Thanks for the additional info. If I find an easy solution will reopen/update this.
