### ISSUE TITLE
Cannot modify port number of web server

### ISSUE THREAD

**Issue by ianco** [bcgov/von-network#289]
Port number is hard coded to `9000`, would be nice to be able to override this if port 9000 is already used.

**Comment by WadeBarnes** [comment]
The web server port can be changed using the `WEB_SERVER_HOST_PORT` environment variable.

See this under https://github.com/bcgov/von-network?tab=readme-ov-file#running-the-network-on-a-vps:

![image](https://github.com/bcgov/von-network/assets/10504350/ad7b8436-a23d-4711-8e8c-6e057f602c66)

**Comment by ianco** [comment]
Ah right I didn't see that, thanks!
