### ISSUE TITLE
BFG cleaner suggestion - [Change to existing git refs]

### ISSUE THREAD

**Issue by ff137** [bcgov/von-network#292]
I noticed when downloading my fork, the repo is ~60MB big. It's coming from the `.git/object` directory, so represent a big file that was previously committed and then deleted. This remains in the git history and makes cloning the repo slow (for us with slow internet, and workflows doing checkouts etc).

The problem file: [`sst_dump.tar.gz`](https://github.com/bcgov/von-network/blob/6f4c168a036aeb20af2fdc6139e57cc59464c325/bin/sst_dump.tar.gz)

The solution: [BFG repo cleaner](https://github.com/rtyley/bfg-repo-cleaner)

___
Requirements: maintainer/admin access with force push permissions.

Warning: Following steps below will edit the git history to completely remove the single large object from git references. If you want to keep that file, don't follow these steps! If you're not sure, make a backup! A backup allows git history changes to be reverted.

Benefit: improves overall efficiency of working with the repository

Cost: Contributors will have to re-synchronize these git history changes by hard resetting their fork (`git reset --hard upstream/main; git push -f`)
___

- Download the BFG jar file: https://rtyley.github.io/bfg-repo-cleaner/
  ```sh
  wget https://repo1.maven.org/maven2/com/madgag/bfg/1.14.0/bfg-1.14.0.jar
  ```
- clone this repo (using mirror flag): 
  ```sh
  git clone --mirror https://github.com/bcgov/von-network.git
  # mkdir backup; cd backup; git clone --mirror https://github.com/bcgov/von-network.git
  ```
- run BFG to remove the large object (selecting only the problem file is safer): 
  ```sh
  java -jar ../path/to/bfg-1.14.0.jar --delete-files sst_dump.tar.gz von-network.git # (deletes only the problem file)
  ```
  ```sh
  Deleted files
  -------------
  
          Filename          Git id            
          ------------------------------------
          sst_dump.tar.gz | 20147dcd (58.1 MB)
  ```
- Changes have not yet been applied. Confirm the clean up: 
  ```sh
  cd von-network.git
  git reflog expire --expire=now --all && git gc --prune=now --aggressive
  ```
- push the changes
  ```sh
  git push --force
  ```

Ta-da 🎉 the 60MB object is now removed from the git history. Repo is now 1.6 MB

Very minor quality of life improvement, and maybe it's more trouble than it's worth, but still thought it's worth sharing! This tool is very helpful for removing large files, and removing passwords files or sensitive keys that have previously been committed and exist in the git history,

It's not possible to make such changes via PR - needs to be force pushed by admin directly. You're welcome to ignore this suggestion, but this is just what I'd do if I was admin ☺️

**Comment by WadeBarnes** [comment]
This has been done.  Note to anyone encountering issues syncing with the repo.  You will need to reset your main branch to match  the new commit history.  The other option is to delete your working copy and re-clone.
