### ISSUE TITLE
Time Out Issue in VON Network StartUp

### ISSUE THREAD

**Issue by gokulsan** [bcgov/von-network#47]
I am getting timeout error in VON Network StartUp despite having good internet connectivity. It was working fine in the first time installation and starting up. 

node3_1    | 2019-03-18 02:12:28,046 | INFO     | zstack.py            (584) | connect | CONNECTION: Node3 looking for Node2 at 172.20.10.12:9703
von-web_1  | ERROR|indy::errors::indy            |                 src/errors/indy.rs:68  | Casting error to ErrorCode: Timeout
von-web_1  | ERROR|indy::services::pool          |           src/services/pool/mod.rs:426 | Pool worker thread finished with error Timeout
von-web_1  | _indy_loop_callback: Function returned error 307
von-web_1  | Traceback (most recent call last):
von-web_1  |   File "server.py", line 295, in <module>
von-web_1  |     loop.run_until_complete(boot())
von-web_1  |   File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
von-web_1  |     return future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
von-web_1  |     result = coro.throw(exc)
von-web_1  |   File "server.py", line 112, in boot
von-web_1  |     await pool.open()
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/von_agent/nodepool.py", line 125, in open
von-web_1  |     self._handle = await pool.open_pool_ledger(self.name, None)
von-web_1  |   File "/home/indy/.local/share/virtualenvs/server-8XoupS0v/lib/python3.5/site-packages/indy/pool.py", line 82, in open_pool_ledger
von-web_1  |     open_pool_ledger.cb)
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
von-web_1  |     yield self  # This tells Task to wait for completion.
von-web_1  |   File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
von-web_1  |     future.result()
von-web_1  |   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
von-web_1  |     raise self._exception
von-web_1  | indy.error.IndyError: ErrorCode.PoolLedgerTimeout
von_von-web_1 exited with code 1

**Comment by WadeBarnes** [comment]
@gokulsan, I just tested out the latest version from a clean build state (on Windows, using Get Bash) and everything is working for me.
```
./manage down
./manage build
./manage start
```

What steps did you take that lead to the error you reported?
What OS are you running?
Are you working at a location were you are behind a proxy?

**Comment by WadeBarnes** [comment]
@gokulsan, There have been additional updates which resolve issues restarting `von-network` instances which could have been part of your problem.  Refer to issue #60 for details.  I'm closing this issue for now.  We can reopen it if you run into the issue again.
