### ISSUE TITLE
Error when running ./manage cli (Docker)

### ISSUE THREAD

**Issue by mhailstone** [bcgov/von-network#64]
When attempting to run the ./manage cli command, the `cp .indy-cli/networks/sandbox/pool_transactions_genesis .indy_client/pool/sandbox/sandbox.txn` command fails. The `.indy-cli/networks/sandbox/pool_transactions_genesis` file does not exist.

https://github.com/bcgov/von-network/blob/51626ceec413a5da3cf7a4919c76c2b685e35eda/scripts/start_client.sh#L17

Changing the command to `cp /home/indy/ledger/sandbox/pool_transactions_genesis .indy_client/pool/sandbox/sandbox.txn` fixed the problem, but not sure if that is what should be done.

**Comment by WadeBarnes** [comment]
@mhailstone, That was the correct thing to do.
