### ISSUE TITLE
Problem in running in the browser the Aries OpenAPI Demo

### ISSUE THREAD

**Issue by lucafra23** [bcgov/von-network#67]
Hi All, I used the demo smoothly for a bit.

Then I closed the browser windows, and tried to use the docker playground again.

The problem I am finding now, is the impossibility for me to launch commands from the new created instances.

I cannot see the text I write, and it really seems something is wrong when setting up the instances.
I don't know the reason, because it has been working smoothly before.

(By the way, I am already logged in into docker)

Here a picture in order for you to better understand my problem:

![Captura de pantalla 2019-07-23 a les 16 14 22](https://user-images.githubusercontent.com/31696035/61719578-80758b80-ad65-11e9-9268-412385a7e4fc.png)

Someone has any ideas on this?

Thanks

**Comment by swcurran** [comment]
There seems to be a problem with the site right now - we're checking.  You
can use https://labs.play-with-docker.com the same way. For that you need a
Docker Hub account.

**Comment by lucafra23** [comment]
Thanks, it seems it is fixed now.

I only have a 500 server error on Alice Agent(in port 8031).What could the problem be? it seems to me to have followed closely the instructions provided.

When I see Alice's logs I get:

#9 Input faber.py invitation details
Alice      | 2019-07-23 15:09:15,243 aries_cloudagent.messaging.models.base ERROR Message validation error:
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
Alice      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/marshmallow/schema.py", line 706, in load
Alice      |     postprocess=True,
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/marshmallow/schema.py", line 866, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'invitation_url': ['Unknown field.'], 'invitation': ['Unknown field.'], 'connection_id': ['Unknown field.']}
Alice      | 2019-07-23 15:09:15,245 aiohttp.server ERROR Error handling request
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 127, in deserialize
Alice      |     return schema.loads(obj) if isinstance(obj, str) else schema.load(obj)
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/marshmallow/schema.py", line 706, in load
Alice      |     postprocess=True,
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/marshmallow/schema.py", line 866, in _do_load
Alice      |     raise exc
Alice      | marshmallow.exceptions.ValidationError: {'invitation_url': ['Unknown field.'], 'invitation': ['Unknown field.'], 'connection_id': ['Unknown field.']}
Alice      |
Alice      | The above exception was the direct cause of the following exception:
Alice      |
Alice      | Traceback (most recent call last):
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
Alice      |     resp = await task
Alice      |   File "/home/indy/.pyenv/versions/3.6.8/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
Alice      |     resp = await handler(request)
Alice      |   File "/home/indy/aries_cloudagent/messaging/connections/routes.py", line 225, in connections_receive_invitation
Alice      |     invitation = ConnectionInvitation.deserialize(invitation_json)
Alice      |   File "/home/indy/aries_cloudagent/messaging/models/base.py", line 130, in deserialize
Alice      |     raise BaseModelError("Schema validation failed") from e
Alice      | aries_cloudagent.messaging.models.base.BaseModelError: Schema validation failed

**Comment by ianco** [comment]
It looks like a problem copying the invitation from Faber to Alice.  Make sure when you copy it you include the enclosing "{ ... }" sqiggly brackets, and make sure there are no line feeds.

**Comment by lucafra23** [comment]
The strange things is there are no line feeds and I made sure I included the brackets..
Here there the my response body I copied and pasted:

```
{
  "connection_id": "6cafe8bb-738a-4390-a3f3-7cb9b6f1b73d",
  "invitation": {
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
    "@id": "36519314-f18c-4c44-ba7e-48e96be185f6",
    "serviceEndpoint": "http://ip172-18-0-14-bkri45ttcgkg00bve47g-8020.direct.labs.play-with-docker.com",
    "recipientKeys": [
      "4sUdUb4Lw9tQYz2tDSsVF5BMgSfLXXDP1Bo9hfHLjmGm"
    ],
    "label": "Faber Agent"
  },
  "invitation_url": "http://ip172-18-0-14-bkri45ttcgkg00bve47g-8020.direct.labs.play-with-docker.com?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiMzY1MTkzMTQtZjE4Yy00YzQ0LWJhN2UtNDhlOTZiZTE4NWY2IiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwOi8vaXAxNzItMTgtMC0xNC1ia3JpNDV0dGNna2cwMGJ2ZTQ3Zy04MDIwLmRpcmVjdC5sYWJzLnBsYXktd2l0aC1kb2NrZXIuY29tIiwgInJlY2lwaWVudEtleXMiOiBbIjRzVWRVYjRMdzl0UVl6MnREU3NWRjVCTWdTZkxYWERQMUJvOWhmSExqbUdtIl0sICJsYWJlbCI6ICJGYWJlciBBZ2VudCJ9"
}

Thanks a lot for your quick answers!
```

**Comment by ianco** [comment]
The part to copy & paste is just the "invitation":

{
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
    "@id": "36519314-f18c-4c44-ba7e-48e96be185f6",
    "serviceEndpoint": "http://ip172-18-0-14-bkri45ttcgkg00bve47g-8020.direct.labs.play-with-docker.com",
    "recipientKeys": [
      "4sUdUb4Lw9tQYz2tDSsVF5BMgSfLXXDP1Bo9hfHLjmGm"
    ],
    "label": "Faber Agent"
  }

**Comment by lucafra23** [comment]
thanks!!

**Comment by swcurran** [comment]
All good now.
