### ISSUE TITLE
/bin/sh -c pip install --no-cache-dir -r server/requirements.txt' returned a non-zero code: 1

### ISSUE THREAD

**Issue by EtricKombat** [bcgov/von-network#75]
While tries to start up the VON network with **"von-network/manage build"** the listed error is happening.

---
**Resulting Output**
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/pyyaml/
  Could not find a version that satisfies the requirement pyyaml~=5.1.1 (from -r server/requirements.txt (line 1)) (from versions: )
No matching distribution found for pyyaml~=5.1.1 (from -r server/requirements.txt (line 1))
The command '/bin/sh -c pip install --no-cache-dir -r server/requirements.txt' returned a non-zero code: 1

---

It seems like docker command **listed below** in _von-network-base_ container is failing

"Cmd":["/bin/sh","-c","pip install --no-cache-dir -r server/requirements.txt"]

---
![docker issue](https://user-images.githubusercontent.com/33585301/65680748-38305d80-e075-11e9-9794-5d27869b280e.JPG)

Can you guys help me resolve this?

**Comment by EtricKombat** [comment]
Was unable to reproduce the same issue from other VM. Hence closing this issue.

**Comment by swcurran** [comment]
Thanks for the update.  It does look like a network issue.

**Comment by EtricKombat** [comment]
![Solution](https://user-images.githubusercontent.com/33585301/66999934-82e14a80-f0f4-11e9-8e02-a230170bf908.JPG)
**Solution :**

*  Locate the config.json file located under the "/root/.docker" , it must be missing.
*  If the file is empty, add { } to the file and save it. If the file itself is missing just  create "config.json" add { } with **echo "{}">>/root/.docker/config.json** command
*  Try the Docker task or command again.

- If you are behind a corporate proxy and you do have the **/root/.docker/config.json** file with contents and you are still facing the above mentioned issue, then:

          sed -i '$ d' /root/.docker/config.json
          echo -e ",\n "\""proxies"\"": {\n\t "\""default"\"": {\n\t\t "\""httpProxy"\"": "\""http://${uname}:${pword}@${prox}:${port}"\"",\n\t\t "\""httpsProxy"\"": "\""https://${uname}:${pword}@${prox}:${port}"\"",\n\t\t "\""noProxy"\"": "\""localhost,127.0.0.0/8,*.local,host.docker.internal"\"" \n\t\t}\n\t}\n}">>/root/.docker/config.json



the sed command removes the "}" from config.json file and echo command adds the proxy variables (proxy variable<username>,<password>,<proxyDNS>,<port> has to be read/input) and add back the removed "}" back to the config.json file.
