### ISSUE TITLE
./manage start should be able to run in background

### ISSUE THREAD

**Issue by TimoGlastra** [bcgov/von-network#86]
The `./manage start` script starts the network with docker compose in detached mode, but then it follows the logs. I think the start command should be runnable in the background. Two possible solutions I can think of:

1. Remove log command from up/start command
Users can still manually run the `./manage logs` command to achieve the same result

2. Allow to pass an `--no-logs` or `--logs false` argument to `./manage start`
This will skip the log command if the `--no-logs` or `--logs false` argument is passed.

I would be happy to create a pr with one of the above solutions.

**Comment by swcurran** [comment]
Hey Timo,

Thanks for connecting.  Agree that something is needed.  I'm not super strong about this, but I'd say go with `--no_logs`. Alternative would be to default to no logs, but allow an `--logs` option, but I'm a little worried that might break things that are counting on the existing behaviour.

@WadeBarnes - any preferences from you?  I'm partial to the default off with the --logs option if it won't break anything in our world.

Timo, if you want to go ahead before Wade responds, make it easy to toggle the default :-).

**Comment by TimoGlastra** [comment]
Great!

I created an initial draft pr. Logging is on by default and can be disabled with `--no_logs`. If it does not break anything this can easily be switched to disable logging by default and enable it with `--log`

**Comment by WadeBarnes** [comment]
After playing with it a bit, I'm partial to starting without logging.  @TimoGlastra, have a look at the changes I made here; https://github.com/WadeBarnes/von-network/tree/feature/manage-start-optional-logging.

**Comment by TimoGlastra** [comment]
I agree. Starting without logging and enabling when needed sounds logical

**Comment by WadeBarnes** [comment]
@TimoGlastra, If you like the direction you can take it and clean it up and maybe add some additional logging to include a note of how to to start with logging when logging is not turned on.

**Comment by TimoGlastra** [comment]
I don't know if this out of scope of the manage script, but as we are already on the topic now, maybe we could make the following of logs also an option?  I'm currently running the von-network in a [github action](https://github.com/ula-aca/ula-aca-plugins/blob/0e3c5b4d9a61c7c40a53d4447bc07a688a6dffc9/.github/workflows/continuous_integration.yml#L191-L192) that exports the docker log as artifact at the end. The manage scripts always runs the `docker-compose logs` with the `-f` param which make it harder to just output the logs to a file. 

I now fix this with a github patch that removes the `-f` from the log command, which is a solution that i'm not a really big fan of...

**Comment by WadeBarnes** [comment]
You'll see my changes wrap the `docker-compose logs` call in a function, which would make what you are suggesting much easier.  Give it a go.

**Comment by WadeBarnes** [comment]
@TimoGlastra, Could you review the changes in https://github.com/bcgov/von-network/pull/91 and see if there is anything else you'd like to change/add?

**Comment by WadeBarnes** [comment]
Done
