### ISSUE TITLE
Problem when running http://playground.playwithdocker.na.xom.com/

### ISSUE THREAD

**Issue by annafang** [bcgov/von-network#98]
when I use http://playground.playwithdocker.na.xom.com/ in chrome, it doesn't allow me type in comment

the error is shown on below.
![image](https://user-images.githubusercontent.com/12975931/75758673-637b4f00-5d6f-11ea-8be5-79b66635bb3c.png)

**Comment by swcurran** [comment]
Sorry - we're not familiar with that service.  You'll have to contact the folks that run that service to get help.

**Comment by WadeBarnes** [comment]
@annafang, Have you tried it http://play-with-von.vonx.io/?

We do not manage the Play with Docker instance you've mentioned.  The behavior you are seeing can be caused by several issues.

**Comment by swcurran** [comment]
Glad to help on von-network issues though! :-)

**Comment by annafang** [comment]
thank you for the suggestion :) @WadeBarnes @swcurran
